exports.words = {
    "bulbasaur": "Pokémon",
    "ivysaur": "Pokémon",
    "venusaur": "Pokémon",
    "venusaurmega": "Pokémon",
    "charmander": "Pokémon",
    "charmeleon": "Pokémon",
    "charizard": "Pokémon",
    "charizardmegax": "Pokémon",
    "charizardmegay": "Pokémon",
    "squirtle": "Pokémon",
    "wartortle": "Pokémon",
    "blastoise": "Pokémon",
    "blastoisemega": "Pokémon",
    "caterpie": "Pokémon",
    "metapod": "Pokémon",
    "butterfree": "Pokémon",
    "weedle": "Pokémon",
    "kakuna": "Pokémon",
    "beedrill": "Pokémon",
    "beedrillmega": "Pokémon",
    "pidgey": "Pokémon",
    "pidgeotto": "Pokémon",
    "pidgeot": "Pokémon",
    "pidgeotmega": "Pokémon",
    "rattata": "Pokémon",
    "raticate": "Pokémon",
    "spearow": "Pokémon",
    "fearow": "Pokémon",
    "ekans": "Pokémon",
    "arbok": "Pokémon",
    "pikachu": "Pokémon",
    "pikachucosplay": "Pokémon",
    "pikachurockstar": "Pokémon",
    "pikachubelle": "Pokémon",
    "pikachupopstar": "Pokémon",
    "pikachuphd": "Pokémon",
    "pikachulibre": "Pokémon",
    "raichu": "Pokémon",
    "sandshrew": "Pokémon",
    "sandslash": "Pokémon",
    "nidoranf": "Pokémon",
    "nidorina": "Pokémon",
    "nidoqueen": "Pokémon",
    "nidoranm": "Pokémon",
    "nidorino": "Pokémon",
    "nidoking": "Pokémon",
    "clefairy": "Pokémon",
    "clefable": "Pokémon",
    "vulpix": "Pokémon",
    "ninetales": "Pokémon",
    "jigglypuff": "Pokémon",
    "wigglytuff": "Pokémon",
    "zubat": "Pokémon",
    "golbat": "Pokémon",
    "oddish": "Pokémon",
    "gloom": "Pokémon",
    "vileplume": "Pokémon",
    "paras": "Pokémon",
    "parasect": "Pokémon",
    "venonat": "Pokémon",
    "venomoth": "Pokémon",
    "diglett": "Pokémon",
    "dugtrio": "Pokémon",
    "meowth": "Pokémon",
    "persian": "Pokémon",
    "psyduck": "Pokémon",
    "golduck": "Pokémon",
    "mankey": "Pokémon",
    "primeape": "Pokémon",
    "growlithe": "Pokémon",
    "arcanine": "Pokémon",
    "poliwag": "Pokémon",
    "poliwhirl": "Pokémon",
    "poliwrath": "Pokémon",
    "abra": "Pokémon",
    "kadabra": "Pokémon",
    "alakazam": "Pokémon",
    "alakazammega": "Pokémon",
    "machop": "Pokémon",
    "machoke": "Pokémon",
    "machamp": "Pokémon",
    "bellsprout": "Pokémon",
    "weepinbell": "Pokémon",
    "victreebel": "Pokémon",
    "tentacool": "Pokémon",
    "tentacruel": "Pokémon",
    "geodude": "Pokémon",
    "graveler": "Pokémon",
    "golem": "Pokémon",
    "ponyta": "Pokémon",
    "rapidash": "Pokémon",
    "slowpoke": "Pokémon",
    "slowbro": "Pokémon",
    "slowbromega": "Pokémon",
    "magnemite": "Pokémon",
    "magneton": "Pokémon",
    "farfetchd": "Pokémon",
    "doduo": "Pokémon",
    "dodrio": "Pokémon",
    "seel": "Pokémon",
    "dewgong": "Pokémon",
    "grimer": "Pokémon",
    "muk": "Pokémon",
    "shellder": "Pokémon",
    "cloyster": "Pokémon",
    "gastly": "Pokémon",
    "haunter": "Pokémon",
    "gengar": "Pokémon",
    "gengarmega": "Pokémon",
    "onix": "Pokémon",
    "drowzee": "Pokémon",
    "hypno": "Pokémon",
    "krabby": "Pokémon",
    "kingler": "Pokémon",
    "voltorb": "Pokémon",
    "electrode": "Pokémon",
    "exeggcute": "Pokémon",
    "exeggutor": "Pokémon",
    "cubone": "Pokémon",
    "marowak": "Pokémon",
    "hitmonlee": "Pokémon",
    "hitmonchan": "Pokémon",
    "lickitung": "Pokémon",
    "koffing": "Pokémon",
    "weezing": "Pokémon",
    "rhyhorn": "Pokémon",
    "rhydon": "Pokémon",
    "chansey": "Pokémon",
    "tangela": "Pokémon",
    "kangaskhan": "Pokémon",
    "kangaskhanmega": "Pokémon",
    "horsea": "Pokémon",
    "seadra": "Pokémon",
    "goldeen": "Pokémon",
    "seaking": "Pokémon",
    "staryu": "Pokémon",
    "starmie": "Pokémon",
    "mrmime": "Pokémon",
    "scyther": "Pokémon",
    "jynx": "Pokémon",
    "electabuzz": "Pokémon",
    "magmar": "Pokémon",
    "pinsir": "Pokémon",
    "pinsirmega": "Pokémon",
    "tauros": "Pokémon",
    "magikarp": "Pokémon",
    "gyarados": "Pokémon",
    "gyaradosmega": "Pokémon",
    "lapras": "Pokémon",
    "ditto": "Pokémon",
    "eevee": "Pokémon",
    "vaporeon": "Pokémon",
    "jolteon": "Pokémon",
    "flareon": "Pokémon",
    "porygon": "Pokémon",
    "omanyte": "Pokémon",
    "omastar": "Pokémon",
    "kabuto": "Pokémon",
    "kabutops": "Pokémon",
    "aerodactyl": "Pokémon",
    "aerodactylmega": "Pokémon",
    "snorlax": "Pokémon",
    "articuno": "Pokémon",
    "zapdos": "Pokémon",
    "moltres": "Pokémon",
    "dratini": "Pokémon",
    "dragonair": "Pokémon",
    "dragonite": "Pokémon",
    "mewtwo": "Pokémon",
    "mewtwomegax": "Pokémon",
    "mewtwomegay": "Pokémon",
    "mew": "Pokémon",
    "chikorita": "Pokémon",
    "bayleef": "Pokémon",
    "meganium": "Pokémon",
    "cyndaquil": "Pokémon",
    "quilava": "Pokémon",
    "typhlosion": "Pokémon",
    "totodile": "Pokémon",
    "croconaw": "Pokémon",
    "feraligatr": "Pokémon",
    "sentret": "Pokémon",
    "furret": "Pokémon",
    "hoothoot": "Pokémon",
    "noctowl": "Pokémon",
    "ledyba": "Pokémon",
    "ledian": "Pokémon",
    "spinarak": "Pokémon",
    "ariados": "Pokémon",
    "crobat": "Pokémon",
    "chinchou": "Pokémon",
    "lanturn": "Pokémon",
    "pichu": "Pokémon",
    "pichuspikyeared": "Pokémon",
    "cleffa": "Pokémon",
    "igglybuff": "Pokémon",
    "togepi": "Pokémon",
    "togetic": "Pokémon",
    "natu": "Pokémon",
    "xatu": "Pokémon",
    "mareep": "Pokémon",
    "flaaffy": "Pokémon",
    "ampharos": "Pokémon",
    "ampharosmega": "Pokémon",
    "bellossom": "Pokémon",
    "marill": "Pokémon",
    "azumarill": "Pokémon",
    "sudowoodo": "Pokémon",
    "politoed": "Pokémon",
    "hoppip": "Pokémon",
    "skiploom": "Pokémon",
    "jumpluff": "Pokémon",
    "aipom": "Pokémon",
    "sunkern": "Pokémon",
    "sunflora": "Pokémon",
    "yanma": "Pokémon",
    "wooper": "Pokémon",
    "quagsire": "Pokémon",
    "espeon": "Pokémon",
    "umbreon": "Pokémon",
    "murkrow": "Pokémon",
    "slowking": "Pokémon",
    "misdreavus": "Pokémon",
    "unown": "Pokémon",
    "wobbuffet": "Pokémon",
    "girafarig": "Pokémon",
    "pineco": "Pokémon",
    "forretress": "Pokémon",
    "dunsparce": "Pokémon",
    "gligar": "Pokémon",
    "steelix": "Pokémon",
    "steelixmega": "Pokémon",
    "snubbull": "Pokémon",
    "granbull": "Pokémon",
    "qwilfish": "Pokémon",
    "scizor": "Pokémon",
    "scizormega": "Pokémon",
    "shuckle": "Pokémon",
    "heracross": "Pokémon",
    "heracrossmega": "Pokémon",
    "sneasel": "Pokémon",
    "teddiursa": "Pokémon",
    "ursaring": "Pokémon",
    "slugma": "Pokémon",
    "magcargo": "Pokémon",
    "swinub": "Pokémon",
    "piloswine": "Pokémon",
    "corsola": "Pokémon",
    "remoraid": "Pokémon",
    "octillery": "Pokémon",
    "delibird": "Pokémon",
    "mantine": "Pokémon",
    "skarmory": "Pokémon",
    "houndour": "Pokémon",
    "houndoom": "Pokémon",
    "houndoommega": "Pokémon",
    "kingdra": "Pokémon",
    "phanpy": "Pokémon",
    "donphan": "Pokémon",
    "porygon2": "Pokémon",
    "stantler": "Pokémon",
    "smeargle": "Pokémon",
    "tyrogue": "Pokémon",
    "hitmontop": "Pokémon",
    "smoochum": "Pokémon",
    "elekid": "Pokémon",
    "magby": "Pokémon",
    "miltank": "Pokémon",
    "blissey": "Pokémon",
    "raikou": "Pokémon",
    "entei": "Pokémon",
    "suicune": "Pokémon",
    "larvitar": "Pokémon",
    "pupitar": "Pokémon",
    "tyranitar": "Pokémon",
    "tyranitarmega": "Pokémon",
    "lugia": "Pokémon",
    "hooh": "Pokémon",
    "celebi": "Pokémon",
    "treecko": "Pokémon",
    "grovyle": "Pokémon",
    "sceptile": "Pokémon",
    "sceptilemega": "Pokémon",
    "torchic": "Pokémon",
    "combusken": "Pokémon",
    "blaziken": "Pokémon",
    "blazikenmega": "Pokémon",
    "mudkip": "Pokémon",
    "marshtomp": "Pokémon",
    "swampert": "Pokémon",
    "swampertmega": "Pokémon",
    "poochyena": "Pokémon",
    "mightyena": "Pokémon",
    "zigzagoon": "Pokémon",
    "linoone": "Pokémon",
    "wurmple": "Pokémon",
    "silcoon": "Pokémon",
    "beautifly": "Pokémon",
    "cascoon": "Pokémon",
    "dustox": "Pokémon",
    "lotad": "Pokémon",
    "lombre": "Pokémon",
    "ludicolo": "Pokémon",
    "seedot": "Pokémon",
    "nuzleaf": "Pokémon",
    "shiftry": "Pokémon",
    "taillow": "Pokémon",
    "swellow": "Pokémon",
    "wingull": "Pokémon",
    "pelipper": "Pokémon",
    "ralts": "Pokémon",
    "kirlia": "Pokémon",
    "gardevoir": "Pokémon",
    "gardevoirmega": "Pokémon",
    "surskit": "Pokémon",
    "masquerain": "Pokémon",
    "shroomish": "Pokémon",
    "breloom": "Pokémon",
    "slakoth": "Pokémon",
    "vigoroth": "Pokémon",
    "slaking": "Pokémon",
    "nincada": "Pokémon",
    "ninjask": "Pokémon",
    "shedinja": "Pokémon",
    "whismur": "Pokémon",
    "loudred": "Pokémon",
    "exploud": "Pokémon",
    "makuhita": "Pokémon",
    "hariyama": "Pokémon",
    "azurill": "Pokémon",
    "nosepass": "Pokémon",
    "skitty": "Pokémon",
    "delcatty": "Pokémon",
    "sableye": "Pokémon",
    "sableyemega": "Pokémon",
    "mawile": "Pokémon",
    "mawilemega": "Pokémon",
    "aron": "Pokémon",
    "lairon": "Pokémon",
    "aggron": "Pokémon",
    "aggronmega": "Pokémon",
    "meditite": "Pokémon",
    "medicham": "Pokémon",
    "medichammega": "Pokémon",
    "electrike": "Pokémon",
    "manectric": "Pokémon",
    "manectricmega": "Pokémon",
    "plusle": "Pokémon",
    "minun": "Pokémon",
    "volbeat": "Pokémon",
    "illumise": "Pokémon",
    "roselia": "Pokémon",
    "gulpin": "Pokémon",
    "swalot": "Pokémon",
    "carvanha": "Pokémon",
    "sharpedo": "Pokémon",
    "sharpedomega": "Pokémon",
    "wailmer": "Pokémon",
    "wailord": "Pokémon",
    "numel": "Pokémon",
    "camerupt": "Pokémon",
    "cameruptmega": "Pokémon",
    "torkoal": "Pokémon",
    "spoink": "Pokémon",
    "grumpig": "Pokémon",
    "spinda": "Pokémon",
    "trapinch": "Pokémon",
    "vibrava": "Pokémon",
    "flygon": "Pokémon",
    "cacnea": "Pokémon",
    "cacturne": "Pokémon",
    "swablu": "Pokémon",
    "altaria": "Pokémon",
    "altariamega": "Pokémon",
    "zangoose": "Pokémon",
    "seviper": "Pokémon",
    "lunatone": "Pokémon",
    "solrock": "Pokémon",
    "barboach": "Pokémon",
    "whiscash": "Pokémon",
    "corphish": "Pokémon",
    "crawdaunt": "Pokémon",
    "baltoy": "Pokémon",
    "claydol": "Pokémon",
    "lileep": "Pokémon",
    "cradily": "Pokémon",
    "anorith": "Pokémon",
    "armaldo": "Pokémon",
    "feebas": "Pokémon",
    "milotic": "Pokémon",
    "castform": "Pokémon",
    "castformsunny": "Pokémon",
    "castformrainy": "Pokémon",
    "castformsnowy": "Pokémon",
    "kecleon": "Pokémon",
    "shuppet": "Pokémon",
    "banette": "Pokémon",
    "banettemega": "Pokémon",
    "duskull": "Pokémon",
    "dusclops": "Pokémon",
    "tropius": "Pokémon",
    "chimecho": "Pokémon",
    "absol": "Pokémon",
    "absolmega": "Pokémon",
    "wynaut": "Pokémon",
    "snorunt": "Pokémon",
    "glalie": "Pokémon",
    "glaliemega": "Pokémon",
    "spheal": "Pokémon",
    "sealeo": "Pokémon",
    "walrein": "Pokémon",
    "clamperl": "Pokémon",
    "huntail": "Pokémon",
    "gorebyss": "Pokémon",
    "relicanth": "Pokémon",
    "luvdisc": "Pokémon",
    "bagon": "Pokémon",
    "shelgon": "Pokémon",
    "salamence": "Pokémon",
    "salamencemega": "Pokémon",
    "beldum": "Pokémon",
    "metang": "Pokémon",
    "metagross": "Pokémon",
    "metagrossmega": "Pokémon",
    "regirock": "Pokémon",
    "regice": "Pokémon",
    "registeel": "Pokémon",
    "latias": "Pokémon",
    "latiasmega": "Pokémon",
    "latios": "Pokémon",
    "latiosmega": "Pokémon",
    "kyogre": "Pokémon",
    "kyogreprimal": "Pokémon",
    "groudon": "Pokémon",
    "groudonprimal": "Pokémon",
    "rayquaza": "Pokémon",
    "rayquazamega": "Pokémon",
    "jirachi": "Pokémon",
    "deoxys": "Pokémon",
    "deoxysattack": "Pokémon",
    "deoxysdefense": "Pokémon",
    "deoxysspeed": "Pokémon",
    "turtwig": "Pokémon",
    "grotle": "Pokémon",
    "torterra": "Pokémon",
    "chimchar": "Pokémon",
    "monferno": "Pokémon",
    "infernape": "Pokémon",
    "piplup": "Pokémon",
    "prinplup": "Pokémon",
    "empoleon": "Pokémon",
    "starly": "Pokémon",
    "staravia": "Pokémon",
    "staraptor": "Pokémon",
    "bidoof": "Pokémon",
    "bibarel": "Pokémon",
    "kricketot": "Pokémon",
    "kricketune": "Pokémon",
    "shinx": "Pokémon",
    "luxio": "Pokémon",
    "luxray": "Pokémon",
    "budew": "Pokémon",
    "roserade": "Pokémon",
    "cranidos": "Pokémon",
    "rampardos": "Pokémon",
    "shieldon": "Pokémon",
    "bastiodon": "Pokémon",
    "burmy": "Pokémon",
    "wormadam": "Pokémon",
    "wormadamsandy": "Pokémon",
    "wormadamtrash": "Pokémon",
    "mothim": "Pokémon",
    "combee": "Pokémon",
    "vespiquen": "Pokémon",
    "pachirisu": "Pokémon",
    "buizel": "Pokémon",
    "floatzel": "Pokémon",
    "cherubi": "Pokémon",
    "cherrim": "Pokémon",
    "cherrimsunshine": "Pokémon",
    "shellos": "Pokémon",
    "gastrodon": "Pokémon",
    "ambipom": "Pokémon",
    "drifloon": "Pokémon",
    "drifblim": "Pokémon",
    "buneary": "Pokémon",
    "lopunny": "Pokémon",
    "lopunnymega": "Pokémon",
    "mismagius": "Pokémon",
    "honchkrow": "Pokémon",
    "glameow": "Pokémon",
    "purugly": "Pokémon",
    "chingling": "Pokémon",
    "stunky": "Pokémon",
    "skuntank": "Pokémon",
    "bronzor": "Pokémon",
    "bronzong": "Pokémon",
    "bonsly": "Pokémon",
    "mimejr": "Pokémon",
    "happiny": "Pokémon",
    "chatot": "Pokémon",
    "spiritomb": "Pokémon",
    "gible": "Pokémon",
    "gabite": "Pokémon",
    "garchomp": "Pokémon",
    "garchompmega": "Pokémon",
    "munchlax": "Pokémon",
    "riolu": "Pokémon",
    "lucario": "Pokémon",
    "lucariomega": "Pokémon",
    "hippopotas": "Pokémon",
    "hippowdon": "Pokémon",
    "skorupi": "Pokémon",
    "drapion": "Pokémon",
    "croagunk": "Pokémon",
    "toxicroak": "Pokémon",
    "carnivine": "Pokémon",
    "finneon": "Pokémon",
    "lumineon": "Pokémon",
    "mantyke": "Pokémon",
    "snover": "Pokémon",
    "abomasnow": "Pokémon",
    "abomasnowmega": "Pokémon",
    "weavile": "Pokémon",
    "magnezone": "Pokémon",
    "lickilicky": "Pokémon",
    "rhyperior": "Pokémon",
    "tangrowth": "Pokémon",
    "electivire": "Pokémon",
    "magmortar": "Pokémon",
    "togekiss": "Pokémon",
    "yanmega": "Pokémon",
    "leafeon": "Pokémon",
    "glaceon": "Pokémon",
    "gliscor": "Pokémon",
    "mamoswine": "Pokémon",
    "porygonz": "Pokémon",
    "gallade": "Pokémon",
    "gallademega": "Pokémon",
    "probopass": "Pokémon",
    "dusknoir": "Pokémon",
    "froslass": "Pokémon",
    "rotom": "Pokémon",
    "rotomheat": "Pokémon",
    "rotomwash": "Pokémon",
    "rotomfrost": "Pokémon",
    "rotomfan": "Pokémon",
    "rotommow": "Pokémon",
    "uxie": "Pokémon",
    "mesprit": "Pokémon",
    "azelf": "Pokémon",
    "dialga": "Pokémon",
    "palkia": "Pokémon",
    "heatran": "Pokémon",
    "regigigas": "Pokémon",
    "giratina": "Pokémon",
    "giratinaorigin": "Pokémon",
    "cresselia": "Pokémon",
    "phione": "Pokémon",
    "manaphy": "Pokémon",
    "darkrai": "Pokémon",
    "shaymin": "Pokémon",
    "shayminsky": "Pokémon",
    "arceus": "Pokémon",
    "arceusbug": "Pokémon",
    "arceusdark": "Pokémon",
    "arceusdragon": "Pokémon",
    "arceuselectric": "Pokémon",
    "arceusfairy": "Pokémon",
    "arceusfighting": "Pokémon",
    "arceusfire": "Pokémon",
    "arceusflying": "Pokémon",
    "arceusghost": "Pokémon",
    "arceusgrass": "Pokémon",
    "arceusground": "Pokémon",
    "arceusice": "Pokémon",
    "arceuspoison": "Pokémon",
    "arceuspsychic": "Pokémon",
    "arceusrock": "Pokémon",
    "arceussteel": "Pokémon",
    "arceuswater": "Pokémon",
    "victini": "Pokémon",
    "snivy": "Pokémon",
    "servine": "Pokémon",
    "serperior": "Pokémon",
    "tepig": "Pokémon",
    "pignite": "Pokémon",
    "emboar": "Pokémon",
    "oshawott": "Pokémon",
    "dewott": "Pokémon",
    "samurott": "Pokémon",
    "patrat": "Pokémon",
    "watchog": "Pokémon",
    "lillipup": "Pokémon",
    "herdier": "Pokémon",
    "stoutland": "Pokémon",
    "purrloin": "Pokémon",
    "liepard": "Pokémon",
    "pansage": "Pokémon",
    "simisage": "Pokémon",
    "pansear": "Pokémon",
    "simisear": "Pokémon",
    "panpour": "Pokémon",
    "simipour": "Pokémon",
    "munna": "Pokémon",
    "musharna": "Pokémon",
    "pidove": "Pokémon",
    "tranquill": "Pokémon",
    "unfezant": "Pokémon",
    "blitzle": "Pokémon",
    "zebstrika": "Pokémon",
    "roggenrola": "Pokémon",
    "boldore": "Pokémon",
    "gigalith": "Pokémon",
    "woobat": "Pokémon",
    "swoobat": "Pokémon",
    "drilbur": "Pokémon",
    "excadrill": "Pokémon",
    "audino": "Pokémon",
    "audinomega": "Pokémon",
    "timburr": "Pokémon",
    "gurdurr": "Pokémon",
    "conkeldurr": "Pokémon",
    "tympole": "Pokémon",
    "palpitoad": "Pokémon",
    "seismitoad": "Pokémon",
    "throh": "Pokémon",
    "sawk": "Pokémon",
    "sewaddle": "Pokémon",
    "swadloon": "Pokémon",
    "leavanny": "Pokémon",
    "venipede": "Pokémon",
    "whirlipede": "Pokémon",
    "scolipede": "Pokémon",
    "cottonee": "Pokémon",
    "whimsicott": "Pokémon",
    "petilil": "Pokémon",
    "lilligant": "Pokémon",
    "basculin": "Pokémon",
    "basculinbluestriped": "Pokémon",
    "sandile": "Pokémon",
    "krokorok": "Pokémon",
    "krookodile": "Pokémon",
    "darumaka": "Pokémon",
    "darmanitan": "Pokémon",
    "darmanitanzen": "Pokémon",
    "maractus": "Pokémon",
    "dwebble": "Pokémon",
    "crustle": "Pokémon",
    "scraggy": "Pokémon",
    "scrafty": "Pokémon",
    "sigilyph": "Pokémon",
    "yamask": "Pokémon",
    "cofagrigus": "Pokémon",
    "tirtouga": "Pokémon",
    "carracosta": "Pokémon",
    "archen": "Pokémon",
    "archeops": "Pokémon",
    "trubbish": "Pokémon",
    "garbodor": "Pokémon",
    "zorua": "Pokémon",
    "zoroark": "Pokémon",
    "minccino": "Pokémon",
    "cinccino": "Pokémon",
    "gothita": "Pokémon",
    "gothorita": "Pokémon",
    "gothitelle": "Pokémon",
    "solosis": "Pokémon",
    "duosion": "Pokémon",
    "reuniclus": "Pokémon",
    "ducklett": "Pokémon",
    "swanna": "Pokémon",
    "vanillite": "Pokémon",
    "vanillish": "Pokémon",
    "vanilluxe": "Pokémon",
    "deerling": "Pokémon",
    "sawsbuck": "Pokémon",
    "emolga": "Pokémon",
    "karrablast": "Pokémon",
    "escavalier": "Pokémon",
    "foongus": "Pokémon",
    "amoonguss": "Pokémon",
    "frillish": "Pokémon",
    "jellicent": "Pokémon",
    "alomomola": "Pokémon",
    "joltik": "Pokémon",
    "galvantula": "Pokémon",
    "ferroseed": "Pokémon",
    "ferrothorn": "Pokémon",
    "klink": "Pokémon",
    "klang": "Pokémon",
    "klinklang": "Pokémon",
    "tynamo": "Pokémon",
    "eelektrik": "Pokémon",
    "eelektross": "Pokémon",
    "elgyem": "Pokémon",
    "beheeyem": "Pokémon",
    "litwick": "Pokémon",
    "lampent": "Pokémon",
    "chandelure": "Pokémon",
    "axew": "Pokémon",
    "fraxure": "Pokémon",
    "haxorus": "Pokémon",
    "cubchoo": "Pokémon",
    "beartic": "Pokémon",
    "cryogonal": "Pokémon",
    "shelmet": "Pokémon",
    "accelgor": "Pokémon",
    "stunfisk": "Pokémon",
    "mienfoo": "Pokémon",
    "mienshao": "Pokémon",
    "druddigon": "Pokémon",
    "golett": "Pokémon",
    "golurk": "Pokémon",
    "pawniard": "Pokémon",
    "bisharp": "Pokémon",
    "bouffalant": "Pokémon",
    "rufflet": "Pokémon",
    "braviary": "Pokémon",
    "vullaby": "Pokémon",
    "mandibuzz": "Pokémon",
    "heatmor": "Pokémon",
    "durant": "Pokémon",
    "deino": "Pokémon",
    "zweilous": "Pokémon",
    "hydreigon": "Pokémon",
    "larvesta": "Pokémon",
    "volcarona": "Pokémon",
    "cobalion": "Pokémon",
    "terrakion": "Pokémon",
    "virizion": "Pokémon",
    "tornadus": "Pokémon",
    "tornadustherian": "Pokémon",
    "thundurus": "Pokémon",
    "thundurustherian": "Pokémon",
    "reshiram": "Pokémon",
    "zekrom": "Pokémon",
    "landorus": "Pokémon",
    "landorustherian": "Pokémon",
    "kyurem": "Pokémon",
    "kyuremblack": "Pokémon",
    "kyuremwhite": "Pokémon",
    "keldeo": "Pokémon",
    "keldeoresolute": "Pokémon",
    "meloetta": "Pokémon",
    "meloettapirouette": "Pokémon",
    "genesect": "Pokémon",
    "genesectdouse": "Pokémon",
    "genesectshock": "Pokémon",
    "genesectburn": "Pokémon",
    "genesectchill": "Pokémon",
    "chespin": "Pokémon",
    "quilladin": "Pokémon",
    "chesnaught": "Pokémon",
    "fennekin": "Pokémon",
    "braixen": "Pokémon",
    "delphox": "Pokémon",
    "froakie": "Pokémon",
    "frogadier": "Pokémon",
    "greninja": "Pokémon",
    "bunnelby": "Pokémon",
    "diggersby": "Pokémon",
    "fletchling": "Pokémon",
    "fletchinder": "Pokémon",
    "talonflame": "Pokémon",
    "scatterbug": "Pokémon",
    "spewpa": "Pokémon",
    "vivillon": "Pokémon",
    "litleo": "Pokémon",
    "pyroar": "Pokémon",
    "flabebe": "Pokémon",
    "floette": "Pokémon",
    "floetteeternalflower": "Pokémon",
    "florges": "Pokémon",
    "skiddo": "Pokémon",
    "gogoat": "Pokémon",
    "pancham": "Pokémon",
    "pangoro": "Pokémon",
    "furfrou": "Pokémon",
    "espurr": "Pokémon",
    "meowstic": "Pokémon",
    "meowsticf": "Pokémon",
    "honedge": "Pokémon",
    "doublade": "Pokémon",
    "aegislash": "Pokémon",
    "aegislashblade": "Pokémon",
    "spritzee": "Pokémon",
    "aromatisse": "Pokémon",
    "swirlix": "Pokémon",
    "slurpuff": "Pokémon",
    "inkay": "Pokémon",
    "malamar": "Pokémon",
    "binacle": "Pokémon",
    "barbaracle": "Pokémon",
    "skrelp": "Pokémon",
    "dragalge": "Pokémon",
    "clauncher": "Pokémon",
    "clawitzer": "Pokémon",
    "helioptile": "Pokémon",
    "heliolisk": "Pokémon",
    "tyrunt": "Pokémon",
    "tyrantrum": "Pokémon",
    "amaura": "Pokémon",
    "aurorus": "Pokémon",
    "sylveon": "Pokémon",
    "hawlucha": "Pokémon",
    "dedenne": "Pokémon",
    "carbink": "Pokémon",
    "goomy": "Pokémon",
    "sliggoo": "Pokémon",
    "goodra": "Pokémon",
    "klefki": "Pokémon",
    "phantump": "Pokémon",
    "trevenant": "Pokémon",
    "pumpkaboo": "Pokémon",
    "pumpkaboosmall": "Pokémon",
    "pumpkaboolarge": "Pokémon",
    "pumpkaboosuper": "Pokémon",
    "gourgeist": "Pokémon",
    "gourgeistsmall": "Pokémon",
    "gourgeistlarge": "Pokémon",
    "gourgeistsuper": "Pokémon",
    "bergmite": "Pokémon",
    "avalugg": "Pokémon",
    "noibat": "Pokémon",
    "noivern": "Pokémon",
    "xerneas": "Pokémon",
    "yveltal": "Pokémon",
    "zygarde": "Pokémon",
    "diancie": "Pokémon",
    "dianciemega": "Pokémon",
    "hoopa": "Pokémon",
    "hoopaunbound": "Pokémon",
    "volcanion": "Pokémon",
    "missingno": "Pokémon",
    "tomohawk": "Pokémon",
    "necturna": "Pokémon",
    "mollux": "Pokémon",
    "aurumoth": "Pokémon",
    "malaconda": "Pokémon",
    "cawmodore": "Pokémon",
    "volkraken": "Pokémon",
    "plasmanta": "Pokémon",
    "naviathan": "Pokémon",
    "syclant": "Pokémon",
    "revenankh": "Pokémon",
    "pyroak": "Pokémon",
    "fidgit": "Pokémon",
    "stratagem": "Pokémon",
    "arghonaut": "Pokémon",
    "kitsunoh": "Pokémon",
    "cyclohm": "Pokémon",
    "colossoil": "Pokémon",
    "krilowatt": "Pokémon",
    "voodoom": "Pokémon",
    "absorb": "Pokémon Move",
    "acid": "Pokémon Move",
    "acidarmor": "Pokémon Move",
    "acidspray": "Pokémon Move",
    "acrobatics": "Pokémon Move",
    "acupressure": "Pokémon Move",
    "aerialace": "Pokémon Move",
    "aeroblast": "Pokémon Move",
    "afteryou": "Pokémon Move",
    "agility": "Pokémon Move",
    "aircutter": "Pokémon Move",
    "airslash": "Pokémon Move",
    "allyswitch": "Pokémon Move",
    "amnesia": "Pokémon Move",
    "ancientpower": "Pokémon Move",
    "aquajet": "Pokémon Move",
    "aquaring": "Pokémon Move",
    "aquatail": "Pokémon Move",
    "armthrust": "Pokémon Move",
    "aromatherapy": "Pokémon Move",
    "aromaticmist": "Pokémon Move",
    "assist": "Pokémon Move",
    "assurance": "Pokémon Move",
    "astonish": "Pokémon Move",
    "attackorder": "Pokémon Move",
    "attract": "Pokémon Move",
    "aurasphere": "Pokémon Move",
    "aurorabeam": "Pokémon Move",
    "autotomize": "Pokémon Move",
    "avalanche": "Pokémon Move",
    "babydolleyes": "Pokémon Move",
    "barrage": "Pokémon Move",
    "barrier": "Pokémon Move",
    "batonpass": "Pokémon Move",
    "beatup": "Pokémon Move",
    "belch": "Pokémon Move",
    "bellydrum": "Pokémon Move",
    "bestow": "Pokémon Move",
    "bide": "Pokémon Move",
    "bind": "Pokémon Move",
    "bite": "Pokémon Move",
    "blastburn": "Pokémon Move",
    "blazekick": "Pokémon Move",
    "blizzard": "Pokémon Move",
    "block": "Pokémon Move",
    "blueflare": "Pokémon Move",
    "bodyslam": "Pokémon Move",
    "boltstrike": "Pokémon Move",
    "boneclub": "Pokémon Move",
    "bonerush": "Pokémon Move",
    "bonemerang": "Pokémon Move",
    "boomburst": "Pokémon Move",
    "bounce": "Pokémon Move",
    "bravebird": "Pokémon Move",
    "brickbreak": "Pokémon Move",
    "brine": "Pokémon Move",
    "bubble": "Pokémon Move",
    "bubblebeam": "Pokémon Move",
    "bugbite": "Pokémon Move",
    "bugbuzz": "Pokémon Move",
    "bulkup": "Pokémon Move",
    "bulldoze": "Pokémon Move",
    "bulletpunch": "Pokémon Move",
    "bulletseed": "Pokémon Move",
    "calmmind": "Pokémon Move",
    "camouflage": "Pokémon Move",
    "captivate": "Pokémon Move",
    "celebrate": "Pokémon Move",
    "charge": "Pokémon Move",
    "chargebeam": "Pokémon Move",
    "charm": "Pokémon Move",
    "chatter": "Pokémon Move",
    "chipaway": "Pokémon Move",
    "circlethrow": "Pokémon Move",
    "clamp": "Pokémon Move",
    "clearsmog": "Pokémon Move",
    "closecombat": "Pokémon Move",
    "coil": "Pokémon Move",
    "cometpunch": "Pokémon Move",
    "confide": "Pokémon Move",
    "confuseray": "Pokémon Move",
    "confusion": "Pokémon Move",
    "constrict": "Pokémon Move",
    "conversion": "Pokémon Move",
    "conversion2": "Pokémon Move",
    "copycat": "Pokémon Move",
    "cosmicpower": "Pokémon Move",
    "cottonguard": "Pokémon Move",
    "cottonspore": "Pokémon Move",
    "counter": "Pokémon Move",
    "covet": "Pokémon Move",
    "crabhammer": "Pokémon Move",
    "craftyshield": "Pokémon Move",
    "crosschop": "Pokémon Move",
    "crosspoison": "Pokémon Move",
    "crunch": "Pokémon Move",
    "crushclaw": "Pokémon Move",
    "crushgrip": "Pokémon Move",
    "curse": "Pokémon Move",
    "cut": "Pokémon Move",
    "darkpulse": "Pokémon Move",
    "darkvoid": "Pokémon Move",
    "dazzlinggleam": "Pokémon Move",
    "defendorder": "Pokémon Move",
    "defensecurl": "Pokémon Move",
    "defog": "Pokémon Move",
    "destinybond": "Pokémon Move",
    "detect": "Pokémon Move",
    "diamondstorm": "Pokémon Move",
    "dig": "Pokémon Move",
    "disable": "Pokémon Move",
    "disarmingvoice": "Pokémon Move",
    "discharge": "Pokémon Move",
    "dive": "Pokémon Move",
    "dizzypunch": "Pokémon Move",
    "doomdesire": "Pokémon Move",
    "doubleedge": "Pokémon Move",
    "doublehit": "Pokémon Move",
    "doublekick": "Pokémon Move",
    "doubleslap": "Pokémon Move",
    "doubleteam": "Pokémon Move",
    "dracometeor": "Pokémon Move",
    "dragonascent": "Pokémon Move",
    "dragonbreath": "Pokémon Move",
    "dragonclaw": "Pokémon Move",
    "dragondance": "Pokémon Move",
    "dragonpulse": "Pokémon Move",
    "dragonrage": "Pokémon Move",
    "dragonrush": "Pokémon Move",
    "dragontail": "Pokémon Move",
    "drainingkiss": "Pokémon Move",
    "drainpunch": "Pokémon Move",
    "dreameater": "Pokémon Move",
    "drillpeck": "Pokémon Move",
    "drillrun": "Pokémon Move",
    "dualchop": "Pokémon Move",
    "dynamicpunch": "Pokémon Move",
    "earthpower": "Pokémon Move",
    "earthquake": "Pokémon Move",
    "echoedvoice": "Pokémon Move",
    "eerieimpulse": "Pokémon Move",
    "eggbomb": "Pokémon Move",
    "electricterrain": "Pokémon Move",
    "electrify": "Pokémon Move",
    "electroball": "Pokémon Move",
    "electroweb": "Pokémon Move",
    "embargo": "Pokémon Move",
    "ember": "Pokémon Move",
    "encore": "Pokémon Move",
    "endeavor": "Pokémon Move",
    "endure": "Pokémon Move",
    "energyball": "Pokémon Move",
    "entrainment": "Pokémon Move",
    "eruption": "Pokémon Move",
    "explosion": "Pokémon Move",
    "extrasensory": "Pokémon Move",
    "extremespeed": "Pokémon Move",
    "facade": "Pokémon Move",
    "feintattack": "Pokémon Move",
    "fairylock": "Pokémon Move",
    "fairywind": "Pokémon Move",
    "fakeout": "Pokémon Move",
    "faketears": "Pokémon Move",
    "falseswipe": "Pokémon Move",
    "featherdance": "Pokémon Move",
    "feint": "Pokémon Move",
    "fellstinger": "Pokémon Move",
    "fierydance": "Pokémon Move",
    "finalgambit": "Pokémon Move",
    "fireblast": "Pokémon Move",
    "firefang": "Pokémon Move",
    "firepledge": "Pokémon Move",
    "firepunch": "Pokémon Move",
    "firespin": "Pokémon Move",
    "fissure": "Pokémon Move",
    "flail": "Pokémon Move",
    "flameburst": "Pokémon Move",
    "flamecharge": "Pokémon Move",
    "flamewheel": "Pokémon Move",
    "flamethrower": "Pokémon Move",
    "flareblitz": "Pokémon Move",
    "flash": "Pokémon Move",
    "flashcannon": "Pokémon Move",
    "flatter": "Pokémon Move",
    "fling": "Pokémon Move",
    "flowershield": "Pokémon Move",
    "fly": "Pokémon Move",
    "flyingpress": "Pokémon Move",
    "focusblast": "Pokémon Move",
    "focusenergy": "Pokémon Move",
    "focuspunch": "Pokémon Move",
    "followme": "Pokémon Move",
    "forcepalm": "Pokémon Move",
    "foresight": "Pokémon Move",
    "forestscurse": "Pokémon Move",
    "foulplay": "Pokémon Move",
    "freezedry": "Pokémon Move",
    "freezeshock": "Pokémon Move",
    "frenzyplant": "Pokémon Move",
    "frostbreath": "Pokémon Move",
    "frustration": "Pokémon Move",
    "furyattack": "Pokémon Move",
    "furycutter": "Pokémon Move",
    "furyswipes": "Pokémon Move",
    "fusionbolt": "Pokémon Move",
    "fusionflare": "Pokémon Move",
    "futuresight": "Pokémon Move",
    "gastroacid": "Pokémon Move",
    "geargrind": "Pokémon Move",
    "geomancy": "Pokémon Move",
    "gigadrain": "Pokémon Move",
    "gigaimpact": "Pokémon Move",
    "glaciate": "Pokémon Move",
    "glare": "Pokémon Move",
    "grassknot": "Pokémon Move",
    "grasspledge": "Pokémon Move",
    "grasswhistle": "Pokémon Move",
    "grassyterrain": "Pokémon Move",
    "gravity": "Pokémon Move",
    "growl": "Pokémon Move",
    "growth": "Pokémon Move",
    "grudge": "Pokémon Move",
    "guardsplit": "Pokémon Move",
    "guardswap": "Pokémon Move",
    "guillotine": "Pokémon Move",
    "gunkshot": "Pokémon Move",
    "gust": "Pokémon Move",
    "gyroball": "Pokémon Move",
    "hail": "Pokémon Move",
    "hammerarm": "Pokémon Move",
    "happyhour": "Pokémon Move",
    "harden": "Pokémon Move",
    "haze": "Pokémon Move",
    "headcharge": "Pokémon Move",
    "headsmash": "Pokémon Move",
    "headbutt": "Pokémon Move",
    "healbell": "Pokémon Move",
    "healblock": "Pokémon Move",
    "healorder": "Pokémon Move",
    "healpulse": "Pokémon Move",
    "healingwish": "Pokémon Move",
    "heartstamp": "Pokémon Move",
    "heartswap": "Pokémon Move",
    "heatcrash": "Pokémon Move",
    "heatwave": "Pokémon Move",
    "heavyslam": "Pokémon Move",
    "helpinghand": "Pokémon Move",
    "hex": "Pokémon Move",
    "hiddenpower": "Pokémon Move",
    "hiddenpowerbug": "Pokémon Move",
    "hiddenpowerdark": "Pokémon Move",
    "hiddenpowerdragon": "Pokémon Move",
    "hiddenpowerelectric": "Pokémon Move",
    "hiddenpowerfighting": "Pokémon Move",
    "hiddenpowerfire": "Pokémon Move",
    "hiddenpowerflying": "Pokémon Move",
    "hiddenpowerghost": "Pokémon Move",
    "hiddenpowergrass": "Pokémon Move",
    "hiddenpowerground": "Pokémon Move",
    "hiddenpowerice": "Pokémon Move",
    "hiddenpowerpoison": "Pokémon Move",
    "hiddenpowerpsychic": "Pokémon Move",
    "hiddenpowerrock": "Pokémon Move",
    "hiddenpowersteel": "Pokémon Move",
    "hiddenpowerwater": "Pokémon Move",
    "highjumpkick": "Pokémon Move",
    "holdback": "Pokémon Move",
    "holdhands": "Pokémon Move",
    "honeclaws": "Pokémon Move",
    "hornattack": "Pokémon Move",
    "horndrill": "Pokémon Move",
    "hornleech": "Pokémon Move",
    "howl": "Pokémon Move",
    "hurricane": "Pokémon Move",
    "hydrocannon": "Pokémon Move",
    "hydropump": "Pokémon Move",
    "hyperbeam": "Pokémon Move",
    "hyperfang": "Pokémon Move",
    "hyperspacefury": "Pokémon Move",
    "hyperspacehole": "Pokémon Move",
    "hypervoice": "Pokémon Move",
    "hypnosis": "Pokémon Move",
    "iceball": "Pokémon Move",
    "icebeam": "Pokémon Move",
    "iceburn": "Pokémon Move",
    "icefang": "Pokémon Move",
    "icepunch": "Pokémon Move",
    "iceshard": "Pokémon Move",
    "iciclecrash": "Pokémon Move",
    "iciclespear": "Pokémon Move",
    "icywind": "Pokémon Move",
    "imprison": "Pokémon Move",
    "incinerate": "Pokémon Move",
    "inferno": "Pokémon Move",
    "infestation": "Pokémon Move",
    "ingrain": "Pokémon Move",
    "iondeluge": "Pokémon Move",
    "irondefense": "Pokémon Move",
    "ironhead": "Pokémon Move",
    "irontail": "Pokémon Move",
    "judgment": "Pokémon Move",
    "jumpkick": "Pokémon Move",
    "karatechop": "Pokémon Move",
    "kinesis": "Pokémon Move",
    "kingsshield": "Pokémon Move",
    "knockoff": "Pokémon Move",
    "landswrath": "Pokémon Move",
    "lastresort": "Pokémon Move",
    "lavaplume": "Pokémon Move",
    "leafblade": "Pokémon Move",
    "leafstorm": "Pokémon Move",
    "leaftornado": "Pokémon Move",
    "leechlife": "Pokémon Move",
    "leechseed": "Pokémon Move",
    "leer": "Pokémon Move",
    "lick": "Pokémon Move",
    "lightofruin": "Pokémon Move",
    "lightscreen": "Pokémon Move",
    "lockon": "Pokémon Move",
    "lovelykiss": "Pokémon Move",
    "lowkick": "Pokémon Move",
    "lowsweep": "Pokémon Move",
    "luckychant": "Pokémon Move",
    "lunardance": "Pokémon Move",
    "lusterpurge": "Pokémon Move",
    "machpunch": "Pokémon Move",
    "magiccoat": "Pokémon Move",
    "magicroom": "Pokémon Move",
    "magicalleaf": "Pokémon Move",
    "magmastorm": "Pokémon Move",
    "magnetbomb": "Pokémon Move",
    "magneticflux": "Pokémon Move",
    "magnetrise": "Pokémon Move",
    "magnitude": "Pokémon Move",
    "matblock": "Pokémon Move",
    "mefirst": "Pokémon Move",
    "meanlook": "Pokémon Move",
    "meditate": "Pokémon Move",
    "megadrain": "Pokémon Move",
    "megakick": "Pokémon Move",
    "megapunch": "Pokémon Move",
    "megahorn": "Pokémon Move",
    "memento": "Pokémon Move",
    "metalburst": "Pokémon Move",
    "metalclaw": "Pokémon Move",
    "metalsound": "Pokémon Move",
    "meteormash": "Pokémon Move",
    "metronome": "Pokémon Item",
    "milkdrink": "Pokémon Move",
    "mimic": "Pokémon Move",
    "mindreader": "Pokémon Move",
    "minimize": "Pokémon Move",
    "miracleeye": "Pokémon Move",
    "mirrorcoat": "Pokémon Move",
    "mirrormove": "Pokémon Move",
    "mirrorshot": "Pokémon Move",
    "mist": "Pokémon Move",
    "mistball": "Pokémon Move",
    "mistyterrain": "Pokémon Move",
    "moonblast": "Pokémon Move",
    "moonlight": "Pokémon Move",
    "morningsun": "Pokémon Move",
    "mudslap": "Pokémon Move",
    "mudbomb": "Pokémon Move",
    "mudshot": "Pokémon Move",
    "mudsport": "Pokémon Move",
    "muddywater": "Pokémon Move",
    "mysticalfire": "Pokémon Move",
    "nastyplot": "Pokémon Move",
    "naturalgift": "Pokémon Move",
    "naturepower": "Pokémon Move",
    "needlearm": "Pokémon Move",
    "nightdaze": "Pokémon Move",
    "nightshade": "Pokémon Move",
    "nightslash": "Pokémon Move",
    "nightmare": "Pokémon Move",
    "nobleroar": "Pokémon Move",
    "nuzzle": "Pokémon Move",
    "oblivionwing": "Pokémon Move",
    "octazooka": "Pokémon Move",
    "odorsleuth": "Pokémon Move",
    "ominouswind": "Pokémon Move",
    "originpulse": "Pokémon Move",
    "outrage": "Pokémon Move",
    "overheat": "Pokémon Move",
    "painsplit": "Pokémon Move",
    "paraboliccharge": "Pokémon Move",
    "partingshot": "Pokémon Move",
    "payday": "Pokémon Move",
    "payback": "Pokémon Move",
    "peck": "Pokémon Move",
    "perishsong": "Pokémon Move",
    "petalblizzard": "Pokémon Move",
    "petaldance": "Pokémon Move",
    "phantomforce": "Pokémon Move",
    "pinmissile": "Pokémon Move",
    "playnice": "Pokémon Move",
    "playrough": "Pokémon Move",
    "pluck": "Pokémon Move",
    "poisonfang": "Pokémon Move",
    "poisongas": "Pokémon Move",
    "poisonjab": "Pokémon Move",
    "poisonpowder": "Pokémon Move",
    "poisonsting": "Pokémon Move",
    "poisontail": "Pokémon Move",
    "pound": "Pokémon Move",
    "powder": "Pokémon Move",
    "powdersnow": "Pokémon Move",
    "powergem": "Pokémon Move",
    "powersplit": "Pokémon Move",
    "powerswap": "Pokémon Move",
    "powertrick": "Pokémon Move",
    "poweruppunch": "Pokémon Move",
    "powerwhip": "Pokémon Move",
    "precipiceblades": "Pokémon Move",
    "present": "Pokémon Move",
    "protect": "Pokémon Move",
    "psybeam": "Pokémon Move",
    "psychup": "Pokémon Move",
    "psychic": "Pokémon Move",
    "psychoboost": "Pokémon Move",
    "psychocut": "Pokémon Move",
    "psychoshift": "Pokémon Move",
    "psyshock": "Pokémon Move",
    "psystrike": "Pokémon Move",
    "psywave": "Pokémon Move",
    "punishment": "Pokémon Move",
    "pursuit": "Pokémon Move",
    "quash": "Pokémon Move",
    "quickattack": "Pokémon Move",
    "quickguard": "Pokémon Move",
    "quiverdance": "Pokémon Move",
    "rage": "Pokémon Move",
    "ragepowder": "Pokémon Move",
    "raindance": "Pokémon Move",
    "rapidspin": "Pokémon Move",
    "razorleaf": "Pokémon Move",
    "razorshell": "Pokémon Move",
    "razorwind": "Pokémon Move",
    "recover": "Pokémon Move",
    "recycle": "Pokémon Move",
    "reflect": "Pokémon Move",
    "reflecttype": "Pokémon Move",
    "refresh": "Pokémon Move",
    "relicsong": "Pokémon Move",
    "rest": "Pokémon Move",
    "retaliate": "Pokémon Move",
    "return": "Pokémon Move",
    "revenge": "Pokémon Move",
    "reversal": "Pokémon Move",
    "roar": "Pokémon Move",
    "roaroftime": "Pokémon Move",
    "rockblast": "Pokémon Move",
    "rockclimb": "Pokémon Move",
    "rockpolish": "Pokémon Move",
    "rockslide": "Pokémon Move",
    "rocksmash": "Pokémon Move",
    "rockthrow": "Pokémon Move",
    "rocktomb": "Pokémon Move",
    "rockwrecker": "Pokémon Move",
    "roleplay": "Pokémon Move",
    "rollingkick": "Pokémon Move",
    "rollout": "Pokémon Move",
    "roost": "Pokémon Move",
    "rototiller": "Pokémon Move",
    "round": "Pokémon Move",
    "sacredfire": "Pokémon Move",
    "sacredsword": "Pokémon Move",
    "safeguard": "Pokémon Move",
    "sandattack": "Pokémon Move",
    "sandtomb": "Pokémon Move",
    "sandstorm": "Pokémon Move",
    "scald": "Pokémon Move",
    "scaryface": "Pokémon Move",
    "scratch": "Pokémon Move",
    "screech": "Pokémon Move",
    "searingshot": "Pokémon Move",
    "secretpower": "Pokémon Move",
    "secretsword": "Pokémon Move",
    "seedbomb": "Pokémon Move",
    "seedflare": "Pokémon Move",
    "seismictoss": "Pokémon Move",
    "selfdestruct": "Pokémon Move",
    "shadowball": "Pokémon Move",
    "shadowclaw": "Pokémon Move",
    "shadowforce": "Pokémon Move",
    "shadowpunch": "Pokémon Move",
    "shadowsneak": "Pokémon Move",
    "sharpen": "Pokémon Move",
    "sheercold": "Pokémon Move",
    "shellsmash": "Pokémon Move",
    "shiftgear": "Pokémon Move",
    "shockwave": "Pokémon Move",
    "signalbeam": "Pokémon Move",
    "silverwind": "Pokémon Move",
    "simplebeam": "Pokémon Move",
    "sing": "Pokémon Move",
    "sketch": "Pokémon Move",
    "skillswap": "Pokémon Move",
    "skullbash": "Pokémon Move",
    "skyattack": "Pokémon Move",
    "skydrop": "Pokémon Move",
    "skyuppercut": "Pokémon Move",
    "slackoff": "Pokémon Move",
    "slam": "Pokémon Move",
    "slash": "Pokémon Move",
    "sleeppowder": "Pokémon Move",
    "sleeptalk": "Pokémon Move",
    "sludge": "Pokémon Move",
    "sludgebomb": "Pokémon Move",
    "sludgewave": "Pokémon Move",
    "smackdown": "Pokémon Move",
    "smellingsalts": "Pokémon Move",
    "smog": "Pokémon Move",
    "smokescreen": "Pokémon Move",
    "snarl": "Pokémon Move",
    "snatch": "Pokémon Move",
    "snore": "Pokémon Move",
    "spikyshield": "Pokémon Move",
    "soak": "Pokémon Move",
    "softboiled": "Pokémon Move",
    "solarbeam": "Pokémon Move",
    "sonicboom": "Pokémon Move",
    "spacialrend": "Pokémon Move",
    "spark": "Pokémon Move",
    "spiderweb": "Pokémon Move",
    "spikecannon": "Pokémon Move",
    "spikes": "Pokémon Move",
    "spitup": "Pokémon Move",
    "spite": "Pokémon Move",
    "splash": "Pokémon Move",
    "spore": "Pokémon Move",
    "stealthrock": "Pokémon Move",
    "steameruption": "Pokémon Move",
    "steelwing": "Pokémon Move",
    "stickyweb": "Pokémon Move",
    "stockpile": "Pokémon Move",
    "stomp": "Pokémon Move",
    "stoneedge": "Pokémon Move",
    "storedpower": "Pokémon Move",
    "stormthrow": "Pokémon Move",
    "steamroller": "Pokémon Move",
    "strength": "Pokémon Move",
    "stringshot": "Pokémon Move",
    "struggle": "Pokémon Move",
    "strugglebug": "Pokémon Move",
    "stunspore": "Pokémon Move",
    "submission": "Pokémon Move",
    "substitute": "Pokémon Move",
    "suckerpunch": "Pokémon Move",
    "sunnyday": "Pokémon Move",
    "superfang": "Pokémon Move",
    "superpower": "Pokémon Move",
    "supersonic": "Pokémon Move",
    "surf": "Pokémon Move",
    "swagger": "Pokémon Move",
    "swallow": "Pokémon Move",
    "sweetkiss": "Pokémon Move",
    "sweetscent": "Pokémon Move",
    "swift": "Pokémon Move",
    "switcheroo": "Pokémon Move",
    "swordsdance": "Pokémon Move",
    "synchronoise": "Pokémon Move",
    "synthesis": "Pokémon Move",
    "tackle": "Pokémon Move",
    "tailglow": "Pokémon Move",
    "tailslap": "Pokémon Move",
    "tailwhip": "Pokémon Move",
    "tailwind": "Pokémon Move",
    "takedown": "Pokémon Move",
    "taunt": "Pokémon Move",
    "technoblast": "Pokémon Move",
    "teeterdance": "Pokémon Move",
    "telekinesis": "Pokémon Move",
    "teleport": "Pokémon Move",
    "thief": "Pokémon Move",
    "thousandarrows": "Pokémon Move",
    "thousandwaves": "Pokémon Move",
    "thrash": "Pokémon Move",
    "thunder": "Pokémon Move",
    "thunderfang": "Pokémon Move",
    "thunderpunch": "Pokémon Move",
    "thundershock": "Pokémon Move",
    "thunderwave": "Pokémon Move",
    "thunderbolt": "Pokémon Move",
    "tickle": "Pokémon Move",
    "topsyturvy": "Pokémon Move",
    "torment": "Pokémon Move",
    "toxic": "Pokémon Move",
    "toxicspikes": "Pokémon Move",
    "transform": "Pokémon Move",
    "triattack": "Pokémon Move",
    "trick": "Pokémon Move",
    "trickortreat": "Pokémon Move",
    "trickroom": "Pokémon Move",
    "triplekick": "Pokémon Move",
    "trumpcard": "Pokémon Move",
    "twineedle": "Pokémon Move",
    "twister": "Pokémon Move",
    "uturn": "Pokémon Move",
    "uproar": "Pokémon Move",
    "vcreate": "Pokémon Move",
    "vacuumwave": "Pokémon Move",
    "venomdrench": "Pokémon Move",
    "venoshock": "Pokémon Move",
    "vicegrip": "Pokémon Move",
    "vinewhip": "Pokémon Move",
    "vitalthrow": "Pokémon Move",
    "voltswitch": "Pokémon Move",
    "volttackle": "Pokémon Move",
    "wakeupslap": "Pokémon Move",
    "watergun": "Pokémon Move",
    "waterpledge": "Pokémon Move",
    "waterpulse": "Pokémon Move",
    "watersport": "Pokémon Move",
    "waterspout": "Pokémon Move",
    "waterfall": "Pokémon Move",
    "watershuriken": "Pokémon Move",
    "weatherball": "Pokémon Move",
    "whirlpool": "Pokémon Move",
    "whirlwind": "Pokémon Move",
    "wideguard": "Pokémon Move",
    "wildcharge": "Pokémon Move",
    "willowisp": "Pokémon Move",
    "wingattack": "Pokémon Move",
    "wish": "Pokémon Move",
    "withdraw": "Pokémon Move",
    "wonderroom": "Pokémon Move",
    "woodhammer": "Pokémon Move",
    "workup": "Pokémon Move",
    "worryseed": "Pokémon Move",
    "wrap": "Pokémon Move",
    "wringout": "Pokémon Move",
    "xscissor": "Pokémon Move",
    "yawn": "Pokémon Move",
    "zapcannon": "Pokémon Move",
    "zenheadbutt": "Pokémon Move",
    "paleowave": "Pokémon Move",
    "shadowstrike": "Pokémon Move",
    "magikarpsrevenge": "Pokémon Move",
    "abomasite": "Pokémon Item",
    "absolite": "Pokémon Item",
    "absorbbulb": "Pokémon Item",
    "adamantorb": "Pokémon Item",
    "aerodactylite": "Pokémon Item",
    "aggronite": "Pokémon Item",
    "aguavberry": "Pokémon Item",
    "airballoon": "Pokémon Item",
    "alakazite": "Pokémon Item",
    "altarianite": "Pokémon Item",
    "ampharosite": "Pokémon Item",
    "apicotberry": "Pokémon Item",
    "armorfossil": "Pokémon Item",
    "aspearberry": "Pokémon Item",
    "assaultvest": "Pokémon Item",
    "audinite": "Pokémon Item",
    "babiriberry": "Pokémon Item",
    "banettite": "Pokémon Item",
    "beedrillite": "Pokémon Item",
    "belueberry": "Pokémon Item",
    "berryjuice": "Pokémon Item",
    "bigroot": "Pokémon Item",
    "bindingband": "Pokémon Item",
    "blackbelt": "Pokémon Item",
    "blacksludge": "Pokémon Item",
    "blackglasses": "Pokémon Item",
    "blastoisinite": "Pokémon Item",
    "blazikenite": "Pokémon Item",
    "blueorb": "Pokémon Item",
    "blukberry": "Pokémon Item",
    "brightpowder": "Pokémon Item",
    "buggem": "Pokémon Item",
    "burndrive": "Pokémon Item",
    "cameruptite": "Pokémon Item",
    "cellbattery": "Pokémon Item",
    "charcoal": "Pokémon Item",
    "charizarditex": "Pokémon Item",
    "charizarditey": "Pokémon Item",
    "chartiberry": "Pokémon Item",
    "cheriberry": "Pokémon Item",
    "cherishball": "Pokémon Item",
    "chestoberry": "Pokémon Item",
    "chilanberry": "Pokémon Item",
    "chilldrive": "Pokémon Item",
    "choiceband": "Pokémon Item",
    "choicescarf": "Pokémon Item",
    "choicespecs": "Pokémon Item",
    "chopleberry": "Pokémon Item",
    "clawfossil": "Pokémon Item",
    "cobaberry": "Pokémon Item",
    "colburberry": "Pokémon Item",
    "cornnberry": "Pokémon Item",
    "coverfossil": "Pokémon Item",
    "custapberry": "Pokémon Item",
    "damprock": "Pokémon Item",
    "darkgem": "Pokémon Item",
    "deepseascale": "Pokémon Item",
    "deepseatooth": "Pokémon Item",
    "destinyknot": "Pokémon Item",
    "diancite": "Pokémon Item",
    "diveball": "Pokémon Item",
    "domefossil": "Pokémon Item",
    "dousedrive": "Pokémon Item",
    "dracoplate": "Pokémon Item",
    "dragonfang": "Pokémon Item",
    "dragongem": "Pokémon Item",
    "dreadplate": "Pokémon Item",
    "dreamball": "Pokémon Item",
    "durinberry": "Pokémon Item",
    "duskball": "Pokémon Item",
    "earthplate": "Pokémon Item",
    "ejectbutton": "Pokémon Item",
    "electirizer": "Pokémon Item",
    "electricgem": "Pokémon Item",
    "energypowder": "Pokémon Item",
    "enigmaberry": "Pokémon Item",
    "eviolite": "Pokémon Item",
    "expertbelt": "Pokémon Item",
    "fairygem": "Pokémon Item",
    "fastball": "Pokémon Item",
    "fightinggem": "Pokémon Item",
    "figyberry": "Pokémon Item",
    "firegem": "Pokémon Item",
    "fistplate": "Pokémon Item",
    "flameorb": "Pokémon Item",
    "flameplate": "Pokémon Item",
    "floatstone": "Pokémon Item",
    "flyinggem": "Pokémon Item",
    "focusband": "Pokémon Item",
    "focussash": "Pokémon Item",
    "friendball": "Pokémon Item",
    "fullincense": "Pokémon Item",
    "galladite": "Pokémon Item",
    "ganlonberry": "Pokémon Item",
    "garchompite": "Pokémon Item",
    "gardevoirite": "Pokémon Item",
    "gengarite": "Pokémon Item",
    "ghostgem": "Pokémon Item",
    "glalitite": "Pokémon Item",
    "grassgem": "Pokémon Item",
    "greatball": "Pokémon Item",
    "grepaberry": "Pokémon Item",
    "gripclaw": "Pokémon Item",
    "griseousorb": "Pokémon Item",
    "groundgem": "Pokémon Item",
    "gyaradosite": "Pokémon Item",
    "habanberry": "Pokémon Item",
    "hardstone": "Pokémon Item",
    "healball": "Pokémon Item",
    "heatrock": "Pokémon Item",
    "heavyball": "Pokémon Item",
    "helixfossil": "Pokémon Item",
    "heracronite": "Pokémon Item",
    "hondewberry": "Pokémon Item",
    "houndoominite": "Pokémon Item",
    "iapapaberry": "Pokémon Item",
    "icegem": "Pokémon Item",
    "icicleplate": "Pokémon Item",
    "icyrock": "Pokémon Item",
    "insectplate": "Pokémon Item",
    "ironball": "Pokémon Item",
    "ironplate": "Pokémon Item",
    "jabocaberry": "Pokémon Item",
    "kasibberry": "Pokémon Item",
    "kebiaberry": "Pokémon Item",
    "keeberry": "Pokémon Item",
    "kelpsyberry": "Pokémon Item",
    "kangaskhanite": "Pokémon Item",
    "kingsrock": "Pokémon Item",
    "laggingtail": "Pokémon Item",
    "lansatberry": "Pokémon Item",
    "latiasite": "Pokémon Item",
    "latiosite": "Pokémon Item",
    "laxincense": "Pokémon Item",
    "leftovers": "Pokémon Item",
    "leppaberry": "Pokémon Item",
    "levelball": "Pokémon Item",
    "liechiberry": "Pokémon Item",
    "lifeorb": "Pokémon Item",
    "lightball": "Pokémon Item",
    "lightclay": "Pokémon Item",
    "lopunnite": "Pokémon Item",
    "loveball": "Pokémon Item",
    "lucarionite": "Pokémon Item",
    "luckypunch": "Pokémon Item",
    "lumberry": "Pokémon Item",
    "luminousmoss": "Pokémon Item",
    "lureball": "Pokémon Item",
    "lustrousorb": "Pokémon Item",
    "luxuryball": "Pokémon Item",
    "machobrace": "Pokémon Item",
    "magnet": "Pokémon Item",
    "magoberry": "Pokémon Item",
    "magostberry": "Pokémon Item",
    "mail": "Pokémon Item",
    "manectite": "Pokémon Item",
    "marangaberry": "Pokémon Item",
    "masterball": "Pokémon Item",
    "mawilite": "Pokémon Item",
    "meadowplate": "Pokémon Item",
    "medichamite": "Pokémon Item",
    "mentalherb": "Pokémon Item",
    "metagrossite": "Pokémon Item",
    "metalcoat": "Pokémon Item",
    "metalpowder": "Pokémon Item",
    "mewtwonitex": "Pokémon Item",
    "mewtwonitey": "Pokémon Item",
    "micleberry": "Pokémon Item",
    "mindplate": "Pokémon Item",
    "miracleseed": "Pokémon Item",
    "moonball": "Pokémon Item",
    "muscleband": "Pokémon Item",
    "mysticwater": "Pokémon Item",
    "nanabberry": "Pokémon Item",
    "nestball": "Pokémon Item",
    "netball": "Pokémon Item",
    "nevermeltice": "Pokémon Item",
    "nomelberry": "Pokémon Item",
    "normalgem": "Pokémon Item",
    "occaberry": "Pokémon Item",
    "oddincense": "Pokémon Item",
    "oldamber": "Pokémon Item",
    "oranberry": "Pokémon Item",
    "pamtreberry": "Pokémon Item",
    "parkball": "Pokémon Item",
    "passhoberry": "Pokémon Item",
    "payapaberry": "Pokémon Item",
    "pechaberry": "Pokémon Item",
    "persimberry": "Pokémon Item",
    "petayaberry": "Pokémon Item",
    "pidgeotite": "Pokémon Item",
    "pinapberry": "Pokémon Item",
    "pinsirite": "Pokémon Item",
    "pixieplate": "Pokémon Item",
    "plumefossil": "Pokémon Item",
    "poisonbarb": "Pokémon Item",
    "poisongem": "Pokémon Item",
    "pokeball": "Pokémon Item",
    "pomegberry": "Pokémon Item",
    "powerherb": "Pokémon Item",
    "premierball": "Pokémon Item",
    "psychicgem": "Pokémon Item",
    "qualotberry": "Pokémon Item",
    "quickball": "Pokémon Item",
    "quickclaw": "Pokémon Item",
    "quickpowder": "Pokémon Item",
    "rabutaberry": "Pokémon Item",
    "rarebone": "Pokémon Item",
    "rawstberry": "Pokémon Item",
    "razorclaw": "Pokémon Item",
    "razorfang": "Pokémon Item",
    "razzberry": "Pokémon Item",
    "redcard": "Pokémon Item",
    "redorb": "Pokémon Item",
    "repeatball": "Pokémon Item",
    "rindoberry": "Pokémon Item",
    "ringtarget": "Pokémon Item",
    "rockgem": "Pokémon Item",
    "rockincense": "Pokémon Item",
    "rockyhelmet": "Pokémon Item",
    "rootfossil": "Pokémon Item",
    "roseincense": "Pokémon Item",
    "roseliberry": "Pokémon Item",
    "rowapberry": "Pokémon Item",
    "sablenite": "Pokémon Item",
    "safariball": "Pokémon Item",
    "safetygoggles": "Pokémon Item",
    "salacberry": "Pokémon Item",
    "salamencite": "Pokémon Item",
    "sceptilite": "Pokémon Item",
    "scizorite": "Pokémon Item",
    "scopelens": "Pokémon Item",
    "seaincense": "Pokémon Item",
    "sharpbeak": "Pokémon Item",
    "sharpedonite": "Pokémon Item",
    "shedshell": "Pokémon Item",
    "shellbell": "Pokémon Item",
    "shockdrive": "Pokémon Item",
    "shucaberry": "Pokémon Item",
    "silkscarf": "Pokémon Item",
    "silverpowder": "Pokémon Item",
    "sitrusberry": "Pokémon Item",
    "skullfossil": "Pokémon Item",
    "skyplate": "Pokémon Item",
    "slowbronite": "Pokémon Item",
    "smoothrock": "Pokémon Item",
    "snowball": "Pokémon Item",
    "softsand": "Pokémon Item",
    "souldew": "Pokémon Item",
    "spelltag": "Pokémon Item",
    "spelonberry": "Pokémon Item",
    "splashplate": "Pokémon Item",
    "spookyplate": "Pokémon Item",
    "sportball": "Pokémon Item",
    "starfberry": "Pokémon Item",
    "steelixite": "Pokémon Item",
    "steelgem": "Pokémon Item",
    "stick": "Pokémon Item",
    "stickybarb": "Pokémon Item",
    "stoneplate": "Pokémon Item",
    "swampertite": "Pokémon Item",
    "tamatoberry": "Pokémon Item",
    "tangaberry": "Pokémon Item",
    "thickclub": "Pokémon Item",
    "timerball": "Pokémon Item",
    "toxicorb": "Pokémon Item",
    "toxicplate": "Pokémon Item",
    "twistedspoon": "Pokémon Item",
    "tyranitarite": "Pokémon Item",
    "ultraball": "Pokémon Item",
    "venusaurite": "Pokémon Item",
    "wacanberry": "Pokémon Item",
    "watergem": "Pokémon Item",
    "watmelberry": "Pokémon Item",
    "waveincense": "Pokémon Item",
    "weaknesspolicy": "Pokémon Item",
    "wepearberry": "Pokémon Item",
    "whiteherb": "Pokémon Item",
    "widelens": "Pokémon Item",
    "wikiberry": "Pokémon Item",
    "wiseglasses": "Pokémon Item",
    "yacheberry": "Pokémon Item",
    "zapplate": "Pokémon Item",
    "zoomlens": "Pokémon Item"
}