exports.words = {
    "Abomasite":"Pokémon Item",
    "Absolite":"Pokémon Item",
    "Absorb Bulb":"Pokémon Item",
    "Adamant Orb":"Pokémon Item",
    "Aerodactylite":"Pokémon Item",
    "Aggronite":"Pokémon Item",
    "Aguav Berry":"Pokémon Item",
    "Air Balloon":"Pokémon Item",
    "Alakazite":"Pokémon Item",
    "Altarianite":"Pokémon Item",
    "Ampharosite":"Pokémon Item",
    "Apicot Berry":"Pokémon Item",
    "Armor Fossil":"Pokémon Item",
    "Aspear Berry":"Pokémon Item",
    "Assault Vest":"Pokémon Item",
    "Audinite":"Pokémon Item",
    "Babiri Berry":"Pokémon Item",
    "Banettite":"Pokémon Item",
    "Beedrillite":"Pokémon Item",
    "Belue Berry":"Pokémon Item",
    "Berry Juice":"Pokémon Item",
    "Big Root":"Pokémon Item",
    "Binding Band":"Pokémon Item",
    "Black Belt":"Pokémon Item",
    "Black Sludge":"Pokémon Item",
    "Black Glasses":"Pokémon Item",
    "Blastoisinite":"Pokémon Item",
    "Blazikenite":"Pokémon Item",
    "Blue Orb":"Pokémon Item",
    "Bluk Berry":"Pokémon Item",
    "BrightPowder":"Pokémon Item",
    "Bug Gem":"Pokémon Item",
    "Burn Drive":"Pokémon Item",
    "Cameruptite":"Pokémon Item",
    "Cell Battery":"Pokémon Item",
    "Charcoal":"Pokémon Item",
    "Charizardite X":"Pokémon Item",
    "Charizardite Y":"Pokémon Item",
    "Charti Berry":"Pokémon Item",
    "Cheri Berry":"Pokémon Item",
    "Cherish Ball":"Pokémon Item",
    "Chesto Berry":"Pokémon Item",
    "Chilan Berry":"Pokémon Item",
    "Chill Drive":"Pokémon Item",
    "Choice Band":"Pokémon Item",
    "Choice Scarf":"Pokémon Item",
    "Choice Specs":"Pokémon Item",
    "Chople Berry":"Pokémon Item",
    "Claw Fossil":"Pokémon Item",
    "Coba Berry":"Pokémon Item",
    "Colbur Berry":"Pokémon Item",
    "Cornn Berry":"Pokémon Item",
    "Cover Fossil":"Pokémon Item",
    "Custap Berry":"Pokémon Item",
    "Damp Rock":"Pokémon Item",
    "Dark Gem":"Pokémon Item",
    "DeepSeaScale":"Pokémon Item",
    "DeepSeaTooth":"Pokémon Item",
    "Destiny Knot":"Pokémon Item",
    "Diancite":"Pokémon Item",
    "Dive Ball":"Pokémon Item",
    "Dome Fossil":"Pokémon Item",
    "Douse Drive":"Pokémon Item",
    "Draco Plate":"Pokémon Item",
    "Dragon Fang":"Pokémon Item",
    "Dragon Gem":"Pokémon Item",
    "Dread Plate":"Pokémon Item",
    "Dream Ball":"Pokémon Item",
    "Durin Berry":"Pokémon Item",
    "Dusk Ball":"Pokémon Item",
    "Earth Plate":"Pokémon Item",
    "Eject Button":"Pokémon Item",
    "Electirizer":"Pokémon Item",
    "Electric Gem":"Pokémon Item",
    "EnergyPowder":"Pokémon Item",
    "Enigma Berry":"Pokémon Item",
    "Eviolite":"Pokémon Item",
    "Expert Belt":"Pokémon Item",
    "Fairy Gem":"Pokémon Item",
    "Fast Ball":"Pokémon Item",
    "Fighting Gem":"Pokémon Item",
    "Figy Berry":"Pokémon Item",
    "Fire Gem":"Pokémon Item",
    "Fist Plate":"Pokémon Item",
    "Flame Orb":"Pokémon Item",
    "Flame Plate":"Pokémon Item",
    "Float Stone":"Pokémon Item",
    "Flying Gem":"Pokémon Item",
    "Focus Band":"Pokémon Item",
    "Focus Sash":"Pokémon Item",
    "Friend Ball":"Pokémon Item",
    "Full Incense":"Pokémon Item",
    "Galladite":"Pokémon Item",
    "Ganlon Berry":"Pokémon Item",
    "Garchompite":"Pokémon Item",
    "Gardevoirite":"Pokémon Item",
    "Gengarite":"Pokémon Item",
    "Ghost Gem":"Pokémon Item",
    "Glalitite":"Pokémon Item",
    "Grass Gem":"Pokémon Item",
    "Great Ball":"Pokémon Item",
    "Grepa Berry":"Pokémon Item",
    "Grip Claw":"Pokémon Item",
    "Griseous Orb":"Pokémon Item",
    "Ground Gem":"Pokémon Item",
    "Gyaradosite":"Pokémon Item",
    "Haban Berry":"Pokémon Item",
    "Hard Stone":"Pokémon Item",
    "Heal Ball":"Pokémon Item",
    "Heat Rock":"Pokémon Item",
    "Heavy Ball":"Pokémon Item",
    "Helix Fossil":"Pokémon Item",
    "Heracronite":"Pokémon Item",
    "Hondew Berry":"Pokémon Item",
    "Houndoominite":"Pokémon Item",
    "Iapapa Berry":"Pokémon Item",
    "Ice Gem":"Pokémon Item",
    "Icicle Plate":"Pokémon Item",
    "Icy Rock":"Pokémon Item",
    "Insect Plate":"Pokémon Item",
    "Iron Ball":"Pokémon Item",
    "Iron Plate":"Pokémon Item",
    "Jaboca Berry":"Pokémon Item",
    "Kasib Berry":"Pokémon Item",
    "Kebia Berry":"Pokémon Item",
    "Kee Berry":"Pokémon Item",
    "Kelpsy Berry":"Pokémon Item",
    "Kangaskhanite":"Pokémon Item",
    "King's Rock":"Pokémon Item",
    "Lagging Tail":"Pokémon Item",
    "Lansat Berry":"Pokémon Item",
    "Latiasite":"Pokémon Item",
    "Latiosite":"Pokémon Item",
    "Lax Incense":"Pokémon Item",
    "Leftovers":"Pokémon Item",
    "Leppa Berry":"Pokémon Item",
    "Level Ball":"Pokémon Item",
    "Liechi Berry":"Pokémon Item",
    "Life Orb":"Pokémon Item",
    "Light Ball":"Pokémon Item",
    "Light Clay":"Pokémon Item",
    "Lopunnite":"Pokémon Item",
    "Love Ball":"Pokémon Item",
    "Lucarionite":"Pokémon Item",
    "Lucky Punch":"Pokémon Item",
    "Lum Berry":"Pokémon Item",
    "Luminous Moss":"Pokémon Item",
    "Lure Ball":"Pokémon Item",
    "Lustrous Orb":"Pokémon Item",
    "Luxury Ball":"Pokémon Item",
    "Macho Brace":"Pokémon Item",
    "Magnet":"Pokémon Item",
    "Mago Berry":"Pokémon Item",
    "Magost Berry":"Pokémon Item",
    "Mail":"Pokémon Item",
    "Manectite":"Pokémon Item",
    "Maranga Berry":"Pokémon Item",
    "Master Ball":"Pokémon Item",
    "Mawilite":"Pokémon Item",
    "Meadow Plate":"Pokémon Item",
    "Medichamite":"Pokémon Item",
    "Mental Herb":"Pokémon Item",
    "Metagrossite":"Pokémon Item",
    "Metal Coat":"Pokémon Item",
    "Metal Powder":"Pokémon Item",
    "Metronome":"Pokémon Move",
    "Mewtwonite X":"Pokémon Item",
    "Mewtwonite Y":"Pokémon Item",
    "Micle Berry":"Pokémon Item",
    "Mind Plate":"Pokémon Item",
    "Miracle Seed":"Pokémon Item",
    "Moon Ball":"Pokémon Item",
    "Muscle Band":"Pokémon Item",
    "Mystic Water":"Pokémon Item",
    "Nanab Berry":"Pokémon Item",
    "Nest Ball":"Pokémon Item",
    "Net Ball":"Pokémon Item",
    "Never-Melt Ice":"Pokémon Item",
    "Nomel Berry":"Pokémon Item",
    "Normal Gem":"Pokémon Item",
    "Occa Berry":"Pokémon Item",
    "Odd Incense":"Pokémon Item",
    "Old Amber":"Pokémon Item",
    "Oran Berry":"Pokémon Item",
    "Pamtre Berry":"Pokémon Item",
    "Park Ball":"Pokémon Item",
    "Passho Berry":"Pokémon Item",
    "Payapa Berry":"Pokémon Item",
    "Pecha Berry":"Pokémon Item",
    "Persim Berry":"Pokémon Item",
    "Petaya Berry":"Pokémon Item",
    "Pidgeotite":"Pokémon Item",
    "Pinap Berry":"Pokémon Item",
    "Pinsirite":"Pokémon Item",
    "Pixie Plate":"Pokémon Item",
    "Plume Fossil":"Pokémon Item",
    "Poison Barb":"Pokémon Item",
    "Poison Gem":"Pokémon Item",
    "Poke Ball":"Pokémon Item",
    "Pomeg Berry":"Pokémon Item",
    "Power Herb":"Pokémon Item",
    "Premier Ball":"Pokémon Item",
    "Psychic Gem":"Pokémon Item",
    "Qualot Berry":"Pokémon Item",
    "Quick Ball":"Pokémon Item",
    "Quick Claw":"Pokémon Item",
    "Quick Powder":"Pokémon Item",
    "Rabuta Berry":"Pokémon Item",
    "Rare Bone":"Pokémon Item",
    "Rawst Berry":"Pokémon Item",
    "Razor Claw":"Pokémon Item",
    "Razor Fang":"Pokémon Item",
    "Razz Berry":"Pokémon Item",
    "Red Card":"Pokémon Item",
    "Red Orb":"Pokémon Item",
    "Repeat Ball":"Pokémon Item",
    "Rindo Berry":"Pokémon Item",
    "Ring Target":"Pokémon Item",
    "Rock Gem":"Pokémon Item",
    "Rock Incense":"Pokémon Item",
    "Rocky Helmet":"Pokémon Item",
    "Root Fossil":"Pokémon Item",
    "Rose Incense":"Pokémon Item",
    "Roseli Berry":"Pokémon Item",
    "Rowap Berry":"Pokémon Item",
    "Sablenite":"Pokémon Item",
    "Safari Ball":"Pokémon Item",
    "Safety Goggles":"Pokémon Item",
    "Salac Berry":"Pokémon Item",
    "Salamencite":"Pokémon Item",
    "Sceptilite":"Pokémon Item",
    "Scizorite":"Pokémon Item",
    "Scope Lens":"Pokémon Item",
    "Sea Incense":"Pokémon Item",
    "Sharp Beak":"Pokémon Item",
    "Sharpedonite":"Pokémon Item",
    "Shed Shell":"Pokémon Item",
    "Shell Bell":"Pokémon Item",
    "Shock Drive":"Pokémon Item",
    "Shuca Berry":"Pokémon Item",
    "Silk Scarf":"Pokémon Item",
    "SilverPowder":"Pokémon Item",
    "Sitrus Berry":"Pokémon Item",
    "Skull Fossil":"Pokémon Item",
    "Sky Plate":"Pokémon Item",
    "Slowbronite":"Pokémon Item",
    "Smooth Rock":"Pokémon Item",
    "Snowball":"Pokémon Item",
    "Soft Sand":"Pokémon Item",
    "Soul Dew":"Pokémon Item",
    "Spell Tag":"Pokémon Item",
    "Spelon Berry":"Pokémon Item",
    "Splash Plate":"Pokémon Item",
    "Spooky Plate":"Pokémon Item",
    "Sport Ball":"Pokémon Item",
    "Starf Berry":"Pokémon Item",
    "Steelixite":"Pokémon Item",
    "Steel Gem":"Pokémon Item",
    "Stick":"Pokémon Item",
    "Sticky Barb":"Pokémon Item",
    "Stone Plate":"Pokémon Item",
    "Swampertite":"Pokémon Item",
    "Tamato Berry":"Pokémon Item",
    "Tanga Berry":"Pokémon Item",
    "Thick Club":"Pokémon Item",
    "Timer Ball":"Pokémon Item",
    "Toxic Orb":"Pokémon Item",
    "Toxic Plate":"Pokémon Item",
    "TwistedSpoon":"Pokémon Item",
    "Tyranitarite":"Pokémon Item",
    "Ultra Ball":"Pokémon Item",
    "Venusaurite":"Pokémon Item",
    "Wacan Berry":"Pokémon Item",
    "Water Gem":"Pokémon Item",
    "Watmel Berry":"Pokémon Item",
    "Wave Incense":"Pokémon Item",
    "Weakness Policy":"Pokémon Item",
    "Wepear Berry":"Pokémon Item",
    "White Herb":"Pokémon Item",
    "Wide Lens":"Pokémon Item",
    "Wiki Berry":"Pokémon Item",
    "Wise Glasses":"Pokémon Item",
    "Yache Berry":"Pokémon Item",
    "Zap Plate":"Pokémon Item",
    "Zoom Lens":"Pokémon Item",
    "Bulbasaur":"Pokémon",
    "Ivysaur":"Pokémon",
    "Venusaur":"Pokémon",
    "Venusaur-Mega":"Pokémon",
    "Charmander":"Pokémon",
    "Charmeleon":"Pokémon",
    "Charizard":"Pokémon",
    "Charizard-Mega-X":"Pokémon",
    "Charizard-Mega-Y":"Pokémon",
    "Squirtle":"Pokémon",
    "Wartortle":"Pokémon",
    "Blastoise":"Pokémon",
    "Blastoise-Mega":"Pokémon",
    "Caterpie":"Pokémon",
    "Metapod":"Pokémon",
    "Butterfree":"Pokémon",
    "Weedle":"Pokémon",
    "Kakuna":"Pokémon",
    "Beedrill":"Pokémon",
    "Beedrill-Mega":"Pokémon",
    "Pidgey":"Pokémon",
    "Pidgeotto":"Pokémon",
    "Pidgeot":"Pokémon",
    "Pidgeot-Mega":"Pokémon",
    "Rattata":"Pokémon",
    "Raticate":"Pokémon",
    "Spearow":"Pokémon",
    "Fearow":"Pokémon",
    "Ekans":"Pokémon",
    "Arbok":"Pokémon",
    "Pikachu":"Pokémon",
    "Pikachu-Cosplay":"Pokémon",
    "Pikachu-Rock-Star":"Pokémon",
    "Pikachu-Belle":"Pokémon",
    "Pikachu-Pop-Star":"Pokémon",
    "Pikachu-PhD":"Pokémon",
    "Pikachu-Libre":"Pokémon",
    "Raichu":"Pokémon",
    "Sandshrew":"Pokémon",
    "Sandslash":"Pokémon",
    "Nidoran-F":"Pokémon",
    "Nidorina":"Pokémon",
    "Nidoqueen":"Pokémon",
    "Nidoran-M":"Pokémon",
    "Nidorino":"Pokémon",
    "Nidoking":"Pokémon",
    "Clefairy":"Pokémon",
    "Clefable":"Pokémon",
    "Vulpix":"Pokémon",
    "Ninetales":"Pokémon",
    "Jigglypuff":"Pokémon",
    "Wigglytuff":"Pokémon",
    "Zubat":"Pokémon",
    "Golbat":"Pokémon",
    "Oddish":"Pokémon",
    "Gloom":"Pokémon",
    "Vileplume":"Pokémon",
    "Paras":"Pokémon",
    "Parasect":"Pokémon",
    "Venonat":"Pokémon",
    "Venomoth":"Pokémon",
    "Diglett":"Pokémon",
    "Dugtrio":"Pokémon",
    "Meowth":"Pokémon",
    "Persian":"Pokémon",
    "Psyduck":"Pokémon",
    "Golduck":"Pokémon",
    "Mankey":"Pokémon",
    "Primeape":"Pokémon",
    "Growlithe":"Pokémon",
    "Arcanine":"Pokémon",
    "Poliwag":"Pokémon",
    "Poliwhirl":"Pokémon",
    "Poliwrath":"Pokémon",
    "Abra":"Pokémon",
    "Kadabra":"Pokémon",
    "Alakazam":"Pokémon",
    "Alakazam-Mega":"Pokémon",
    "Machop":"Pokémon",
    "Machoke":"Pokémon",
    "Machamp":"Pokémon",
    "Bellsprout":"Pokémon",
    "Weepinbell":"Pokémon",
    "Victreebel":"Pokémon",
    "Tentacool":"Pokémon",
    "Tentacruel":"Pokémon",
    "Geodude":"Pokémon",
    "Graveler":"Pokémon",
    "Golem":"Pokémon",
    "Ponyta":"Pokémon",
    "Rapidash":"Pokémon",
    "Slowpoke":"Pokémon",
    "Slowbro":"Pokémon",
    "Slowbro-Mega":"Pokémon",
    "Magnemite":"Pokémon",
    "Magneton":"Pokémon",
    "Farfetch'd":"Pokémon",
    "Doduo":"Pokémon",
    "Dodrio":"Pokémon",
    "Seel":"Pokémon",
    "Dewgong":"Pokémon",
    "Grimer":"Pokémon",
    "Muk":"Pokémon",
    "Shellder":"Pokémon",
    "Cloyster":"Pokémon",
    "Gastly":"Pokémon",
    "Haunter":"Pokémon",
    "Gengar":"Pokémon",
    "Gengar-Mega":"Pokémon",
    "Onix":"Pokémon",
    "Drowzee":"Pokémon",
    "Hypno":"Pokémon",
    "Krabby":"Pokémon",
    "Kingler":"Pokémon",
    "Voltorb":"Pokémon",
    "Electrode":"Pokémon",
    "Exeggcute":"Pokémon",
    "Exeggutor":"Pokémon",
    "Cubone":"Pokémon",
    "Marowak":"Pokémon",
    "Hitmonlee":"Pokémon",
    "Hitmonchan":"Pokémon",
    "Lickitung":"Pokémon",
    "Koffing":"Pokémon",
    "Weezing":"Pokémon",
    "Rhyhorn":"Pokémon",
    "Rhydon":"Pokémon",
    "Chansey":"Pokémon",
    "Tangela":"Pokémon",
    "Kangaskhan":"Pokémon",
    "Kangaskhan-Mega":"Pokémon",
    "Horsea":"Pokémon",
    "Seadra":"Pokémon",
    "Goldeen":"Pokémon",
    "Seaking":"Pokémon",
    "Staryu":"Pokémon",
    "Starmie":"Pokémon",
    "Mr. Mime":"Pokémon",
    "Scyther":"Pokémon",
    "Jynx":"Pokémon",
    "Electabuzz":"Pokémon",
    "Magmar":"Pokémon",
    "Pinsir":"Pokémon",
    "Pinsir-Mega":"Pokémon",
    "Tauros":"Pokémon",
    "Magikarp":"Pokémon",
    "Gyarados":"Pokémon",
    "Gyarados-Mega":"Pokémon",
    "Lapras":"Pokémon",
    "Ditto":"Pokémon",
    "Eevee":"Pokémon",
    "Vaporeon":"Pokémon",
    "Jolteon":"Pokémon",
    "Flareon":"Pokémon",
    "Porygon":"Pokémon",
    "Omanyte":"Pokémon",
    "Omastar":"Pokémon",
    "Kabuto":"Pokémon",
    "Kabutops":"Pokémon",
    "Aerodactyl":"Pokémon",
    "Aerodactyl-Mega":"Pokémon",
    "Snorlax":"Pokémon",
    "Articuno":"Pokémon",
    "Zapdos":"Pokémon",
    "Moltres":"Pokémon",
    "Dratini":"Pokémon",
    "Dragonair":"Pokémon",
    "Dragonite":"Pokémon",
    "Mewtwo":"Pokémon",
    "Mewtwo-Mega-X":"Pokémon",
    "Mewtwo-Mega-Y":"Pokémon",
    "Mew":"Pokémon",
    "Chikorita":"Pokémon",
    "Bayleef":"Pokémon",
    "Meganium":"Pokémon",
    "Cyndaquil":"Pokémon",
    "Quilava":"Pokémon",
    "Typhlosion":"Pokémon",
    "Totodile":"Pokémon",
    "Croconaw":"Pokémon",
    "Feraligatr":"Pokémon",
    "Sentret":"Pokémon",
    "Furret":"Pokémon",
    "Hoothoot":"Pokémon",
    "Noctowl":"Pokémon",
    "Ledyba":"Pokémon",
    "Ledian":"Pokémon",
    "Spinarak":"Pokémon",
    "Ariados":"Pokémon",
    "Crobat":"Pokémon",
    "Chinchou":"Pokémon",
    "Lanturn":"Pokémon",
    "Pichu":"Pokémon",
    "Pichu-Spiky-eared":"Pokémon",
    "Cleffa":"Pokémon",
    "Igglybuff":"Pokémon",
    "Togepi":"Pokémon",
    "Togetic":"Pokémon",
    "Natu":"Pokémon",
    "Xatu":"Pokémon",
    "Mareep":"Pokémon",
    "Flaaffy":"Pokémon",
    "Ampharos":"Pokémon",
    "Ampharos-Mega":"Pokémon",
    "Bellossom":"Pokémon",
    "Marill":"Pokémon",
    "Azumarill":"Pokémon",
    "Sudowoodo":"Pokémon",
    "Politoed":"Pokémon",
    "Hoppip":"Pokémon",
    "Skiploom":"Pokémon",
    "Jumpluff":"Pokémon",
    "Aipom":"Pokémon",
    "Sunkern":"Pokémon",
    "Sunflora":"Pokémon",
    "Yanma":"Pokémon",
    "Wooper":"Pokémon",
    "Quagsire":"Pokémon",
    "Espeon":"Pokémon",
    "Umbreon":"Pokémon",
    "Murkrow":"Pokémon",
    "Slowking":"Pokémon",
    "Misdreavus":"Pokémon",
    "Unown":"Pokémon",
    "Wobbuffet":"Pokémon",
    "Girafarig":"Pokémon",
    "Pineco":"Pokémon",
    "Forretress":"Pokémon",
    "Dunsparce":"Pokémon",
    "Gligar":"Pokémon",
    "Steelix":"Pokémon",
    "Steelix-Mega":"Pokémon",
    "Snubbull":"Pokémon",
    "Granbull":"Pokémon",
    "Qwilfish":"Pokémon",
    "Scizor":"Pokémon",
    "Scizor-Mega":"Pokémon",
    "Shuckle":"Pokémon",
    "Heracross":"Pokémon",
    "Heracross-Mega":"Pokémon",
    "Sneasel":"Pokémon",
    "Teddiursa":"Pokémon",
    "Ursaring":"Pokémon",
    "Slugma":"Pokémon",
    "Magcargo":"Pokémon",
    "Swinub":"Pokémon",
    "Piloswine":"Pokémon",
    "Corsola":"Pokémon",
    "Remoraid":"Pokémon",
    "Octillery":"Pokémon",
    "Delibird":"Pokémon",
    "Mantine":"Pokémon",
    "Skarmory":"Pokémon",
    "Houndour":"Pokémon",
    "Houndoom":"Pokémon",
    "Houndoom-Mega":"Pokémon",
    "Kingdra":"Pokémon",
    "Phanpy":"Pokémon",
    "Donphan":"Pokémon",
    "Porygon2":"Pokémon",
    "Stantler":"Pokémon",
    "Smeargle":"Pokémon",
    "Tyrogue":"Pokémon",
    "Hitmontop":"Pokémon",
    "Smoochum":"Pokémon",
    "Elekid":"Pokémon",
    "Magby":"Pokémon",
    "Miltank":"Pokémon",
    "Blissey":"Pokémon",
    "Raikou":"Pokémon",
    "Entei":"Pokémon",
    "Suicune":"Pokémon",
    "Larvitar":"Pokémon",
    "Pupitar":"Pokémon",
    "Tyranitar":"Pokémon",
    "Tyranitar-Mega":"Pokémon",
    "Lugia":"Pokémon",
    "Ho-Oh":"Pokémon",
    "Celebi":"Pokémon",
    "Treecko":"Pokémon",
    "Grovyle":"Pokémon",
    "Sceptile":"Pokémon",
    "Sceptile-Mega":"Pokémon",
    "Torchic":"Pokémon",
    "Combusken":"Pokémon",
    "Blaziken":"Pokémon",
    "Blaziken-Mega":"Pokémon",
    "Mudkip":"Pokémon",
    "Marshtomp":"Pokémon",
    "Swampert":"Pokémon",
    "Swampert-Mega":"Pokémon",
    "Poochyena":"Pokémon",
    "Mightyena":"Pokémon",
    "Zigzagoon":"Pokémon",
    "Linoone":"Pokémon",
    "Wurmple":"Pokémon",
    "Silcoon":"Pokémon",
    "Beautifly":"Pokémon",
    "Cascoon":"Pokémon",
    "Dustox":"Pokémon",
    "Lotad":"Pokémon",
    "Lombre":"Pokémon",
    "Ludicolo":"Pokémon",
    "Seedot":"Pokémon",
    "Nuzleaf":"Pokémon",
    "Shiftry":"Pokémon",
    "Taillow":"Pokémon",
    "Swellow":"Pokémon",
    "Wingull":"Pokémon",
    "Pelipper":"Pokémon",
    "Ralts":"Pokémon",
    "Kirlia":"Pokémon",
    "Gardevoir":"Pokémon",
    "Gardevoir-Mega":"Pokémon",
    "Surskit":"Pokémon",
    "Masquerain":"Pokémon",
    "Shroomish":"Pokémon",
    "Breloom":"Pokémon",
    "Slakoth":"Pokémon",
    "Vigoroth":"Pokémon",
    "Slaking":"Pokémon",
    "Nincada":"Pokémon",
    "Ninjask":"Pokémon",
    "Shedinja":"Pokémon",
    "Whismur":"Pokémon",
    "Loudred":"Pokémon",
    "Exploud":"Pokémon",
    "Makuhita":"Pokémon",
    "Hariyama":"Pokémon",
    "Azurill":"Pokémon",
    "Nosepass":"Pokémon",
    "Skitty":"Pokémon",
    "Delcatty":"Pokémon",
    "Sableye":"Pokémon",
    "Sableye-Mega":"Pokémon",
    "Mawile":"Pokémon",
    "Mawile-Mega":"Pokémon",
    "Aron":"Pokémon",
    "Lairon":"Pokémon",
    "Aggron":"Pokémon",
    "Aggron-Mega":"Pokémon",
    "Meditite":"Pokémon",
    "Medicham":"Pokémon",
    "Medicham-Mega":"Pokémon",
    "Electrike":"Pokémon",
    "Manectric":"Pokémon",
    "Manectric-Mega":"Pokémon",
    "Plusle":"Pokémon",
    "Minun":"Pokémon",
    "Volbeat":"Pokémon",
    "Illumise":"Pokémon",
    "Roselia":"Pokémon",
    "Gulpin":"Pokémon",
    "Swalot":"Pokémon",
    "Carvanha":"Pokémon",
    "Sharpedo":"Pokémon",
    "Sharpedo-Mega":"Pokémon",
    "Wailmer":"Pokémon",
    "Wailord":"Pokémon",
    "Numel":"Pokémon",
    "Camerupt":"Pokémon",
    "Camerupt-Mega":"Pokémon",
    "Torkoal":"Pokémon",
    "Spoink":"Pokémon",
    "Grumpig":"Pokémon",
    "Spinda":"Pokémon",
    "Trapinch":"Pokémon",
    "Vibrava":"Pokémon",
    "Flygon":"Pokémon",
    "Cacnea":"Pokémon",
    "Cacturne":"Pokémon",
    "Swablu":"Pokémon",
    "Altaria":"Pokémon",
    "Altaria-Mega":"Pokémon",
    "Zangoose":"Pokémon",
    "Seviper":"Pokémon",
    "Lunatone":"Pokémon",
    "Solrock":"Pokémon",
    "Barboach":"Pokémon",
    "Whiscash":"Pokémon",
    "Corphish":"Pokémon",
    "Crawdaunt":"Pokémon",
    "Baltoy":"Pokémon",
    "Claydol":"Pokémon",
    "Lileep":"Pokémon",
    "Cradily":"Pokémon",
    "Anorith":"Pokémon",
    "Armaldo":"Pokémon",
    "Feebas":"Pokémon",
    "Milotic":"Pokémon",
    "Castform":"Pokémon",
    "Castform-Sunny":"Pokémon",
    "Castform-Rainy":"Pokémon",
    "Castform-Snowy":"Pokémon",
    "Kecleon":"Pokémon",
    "Shuppet":"Pokémon",
    "Banette":"Pokémon",
    "Banette-Mega":"Pokémon",
    "Duskull":"Pokémon",
    "Dusclops":"Pokémon",
    "Tropius":"Pokémon",
    "Chimecho":"Pokémon",
    "Absol":"Pokémon",
    "Absol-Mega":"Pokémon",
    "Wynaut":"Pokémon",
    "Snorunt":"Pokémon",
    "Glalie":"Pokémon",
    "Glalie-Mega":"Pokémon",
    "Spheal":"Pokémon",
    "Sealeo":"Pokémon",
    "Walrein":"Pokémon",
    "Clamperl":"Pokémon",
    "Huntail":"Pokémon",
    "Gorebyss":"Pokémon",
    "Relicanth":"Pokémon",
    "Luvdisc":"Pokémon",
    "Bagon":"Pokémon",
    "Shelgon":"Pokémon",
    "Salamence":"Pokémon",
    "Salamence-Mega":"Pokémon",
    "Beldum":"Pokémon",
    "Metang":"Pokémon",
    "Metagross":"Pokémon",
    "Metagross-Mega":"Pokémon",
    "Regirock":"Pokémon",
    "Regice":"Pokémon",
    "Registeel":"Pokémon",
    "Latias":"Pokémon",
    "Latias-Mega":"Pokémon",
    "Latios":"Pokémon",
    "Latios-Mega":"Pokémon",
    "Kyogre":"Pokémon",
    "Kyogre-Primal":"Pokémon",
    "Groudon":"Pokémon",
    "Groudon-Primal":"Pokémon",
    "Rayquaza":"Pokémon",
    "Rayquaza-Mega":"Pokémon",
    "Jirachi":"Pokémon",
    "Deoxys":"Pokémon",
    "Deoxys-Attack":"Pokémon",
    "Deoxys-Defense":"Pokémon",
    "Deoxys-Speed":"Pokémon",
    "Turtwig":"Pokémon",
    "Grotle":"Pokémon",
    "Torterra":"Pokémon",
    "Chimchar":"Pokémon",
    "Monferno":"Pokémon",
    "Infernape":"Pokémon",
    "Piplup":"Pokémon",
    "Prinplup":"Pokémon",
    "Empoleon":"Pokémon",
    "Starly":"Pokémon",
    "Staravia":"Pokémon",
    "Staraptor":"Pokémon",
    "Bidoof":"Pokémon",
    "Bibarel":"Pokémon",
    "Kricketot":"Pokémon",
    "Kricketune":"Pokémon",
    "Shinx":"Pokémon",
    "Luxio":"Pokémon",
    "Luxray":"Pokémon",
    "Budew":"Pokémon",
    "Roserade":"Pokémon",
    "Cranidos":"Pokémon",
    "Rampardos":"Pokémon",
    "Shieldon":"Pokémon",
    "Bastiodon":"Pokémon",
    "Burmy":"Pokémon",
    "Wormadam":"Pokémon",
    "Wormadam-Sandy":"Pokémon",
    "Wormadam-Trash":"Pokémon",
    "Mothim":"Pokémon",
    "Combee":"Pokémon",
    "Vespiquen":"Pokémon",
    "Pachirisu":"Pokémon",
    "Buizel":"Pokémon",
    "Floatzel":"Pokémon",
    "Cherubi":"Pokémon",
    "Cherrim":"Pokémon",
    "Cherrim-Sunshine":"Pokémon",
    "Shellos":"Pokémon",
    "Gastrodon":"Pokémon",
    "Ambipom":"Pokémon",
    "Drifloon":"Pokémon",
    "Drifblim":"Pokémon",
    "Buneary":"Pokémon",
    "Lopunny":"Pokémon",
    "Lopunny-Mega":"Pokémon",
    "Mismagius":"Pokémon",
    "Honchkrow":"Pokémon",
    "Glameow":"Pokémon",
    "Purugly":"Pokémon",
    "Chingling":"Pokémon",
    "Stunky":"Pokémon",
    "Skuntank":"Pokémon",
    "Bronzor":"Pokémon",
    "Bronzong":"Pokémon",
    "Bonsly":"Pokémon",
    "Mime Jr.":"Pokémon",
    "Happiny":"Pokémon",
    "Chatot":"Pokémon",
    "Spiritomb":"Pokémon",
    "Gible":"Pokémon",
    "Gabite":"Pokémon",
    "Garchomp":"Pokémon",
    "Garchomp-Mega":"Pokémon",
    "Munchlax":"Pokémon",
    "Riolu":"Pokémon",
    "Lucario":"Pokémon",
    "Lucario-Mega":"Pokémon",
    "Hippopotas":"Pokémon",
    "Hippowdon":"Pokémon",
    "Skorupi":"Pokémon",
    "Drapion":"Pokémon",
    "Croagunk":"Pokémon",
    "Toxicroak":"Pokémon",
    "Carnivine":"Pokémon",
    "Finneon":"Pokémon",
    "Lumineon":"Pokémon",
    "Mantyke":"Pokémon",
    "Snover":"Pokémon",
    "Abomasnow":"Pokémon",
    "Abomasnow-Mega":"Pokémon",
    "Weavile":"Pokémon",
    "Magnezone":"Pokémon",
    "Lickilicky":"Pokémon",
    "Rhyperior":"Pokémon",
    "Tangrowth":"Pokémon",
    "Electivire":"Pokémon",
    "Magmortar":"Pokémon",
    "Togekiss":"Pokémon",
    "Yanmega":"Pokémon",
    "Leafeon":"Pokémon",
    "Glaceon":"Pokémon",
    "Gliscor":"Pokémon",
    "Mamoswine":"Pokémon",
    "Porygon-Z":"Pokémon",
    "Gallade":"Pokémon",
    "Gallade-Mega":"Pokémon",
    "Probopass":"Pokémon",
    "Dusknoir":"Pokémon",
    "Froslass":"Pokémon",
    "Rotom":"Pokémon",
    "Rotom-Heat":"Pokémon",
    "Rotom-Wash":"Pokémon",
    "Rotom-Frost":"Pokémon",
    "Rotom-Fan":"Pokémon",
    "Rotom-Mow":"Pokémon",
    "Uxie":"Pokémon",
    "Mesprit":"Pokémon",
    "Azelf":"Pokémon",
    "Dialga":"Pokémon",
    "Palkia":"Pokémon",
    "Heatran":"Pokémon",
    "Regigigas":"Pokémon",
    "Giratina":"Pokémon",
    "Giratina-Origin":"Pokémon",
    "Cresselia":"Pokémon",
    "Phione":"Pokémon",
    "Manaphy":"Pokémon",
    "Darkrai":"Pokémon",
    "Shaymin":"Pokémon",
    "Shaymin-Sky":"Pokémon",
    "Arceus":"Pokémon",
    "Arceus-Bug":"Pokémon",
    "Arceus-Dark":"Pokémon",
    "Arceus-Dragon":"Pokémon",
    "Arceus-Electric":"Pokémon",
    "Arceus-Fairy":"Pokémon",
    "Arceus-Fighting":"Pokémon",
    "Arceus-Fire":"Pokémon",
    "Arceus-Flying":"Pokémon",
    "Arceus-Ghost":"Pokémon",
    "Arceus-Grass":"Pokémon",
    "Arceus-Ground":"Pokémon",
    "Arceus-Ice":"Pokémon",
    "Arceus-Poison":"Pokémon",
    "Arceus-Psychic":"Pokémon",
    "Arceus-Rock":"Pokémon",
    "Arceus-Steel":"Pokémon",
    "Arceus-Water":"Pokémon",
    "Victini":"Pokémon",
    "Snivy":"Pokémon",
    "Servine":"Pokémon",
    "Serperior":"Pokémon",
    "Tepig":"Pokémon",
    "Pignite":"Pokémon",
    "Emboar":"Pokémon",
    "Oshawott":"Pokémon",
    "Dewott":"Pokémon",
    "Samurott":"Pokémon",
    "Patrat":"Pokémon",
    "Watchog":"Pokémon",
    "Lillipup":"Pokémon",
    "Herdier":"Pokémon",
    "Stoutland":"Pokémon",
    "Purrloin":"Pokémon",
    "Liepard":"Pokémon",
    "Pansage":"Pokémon",
    "Simisage":"Pokémon",
    "Pansear":"Pokémon",
    "Simisear":"Pokémon",
    "Panpour":"Pokémon",
    "Simipour":"Pokémon",
    "Munna":"Pokémon",
    "Musharna":"Pokémon",
    "Pidove":"Pokémon",
    "Tranquill":"Pokémon",
    "Unfezant":"Pokémon",
    "Blitzle":"Pokémon",
    "Zebstrika":"Pokémon",
    "Roggenrola":"Pokémon",
    "Boldore":"Pokémon",
    "Gigalith":"Pokémon",
    "Woobat":"Pokémon",
    "Swoobat":"Pokémon",
    "Drilbur":"Pokémon",
    "Excadrill":"Pokémon",
    "Audino":"Pokémon",
    "Audino-Mega":"Pokémon",
    "Timburr":"Pokémon",
    "Gurdurr":"Pokémon",
    "Conkeldurr":"Pokémon",
    "Tympole":"Pokémon",
    "Palpitoad":"Pokémon",
    "Seismitoad":"Pokémon",
    "Throh":"Pokémon",
    "Sawk":"Pokémon",
    "Sewaddle":"Pokémon",
    "Swadloon":"Pokémon",
    "Leavanny":"Pokémon",
    "Venipede":"Pokémon",
    "Whirlipede":"Pokémon",
    "Scolipede":"Pokémon",
    "Cottonee":"Pokémon",
    "Whimsicott":"Pokémon",
    "Petilil":"Pokémon",
    "Lilligant":"Pokémon",
    "Basculin":"Pokémon",
    "Basculin-Blue-Striped":"Pokémon",
    "Sandile":"Pokémon",
    "Krokorok":"Pokémon",
    "Krookodile":"Pokémon",
    "Darumaka":"Pokémon",
    "Darmanitan":"Pokémon",
    "Darmanitan-Zen":"Pokémon",
    "Maractus":"Pokémon",
    "Dwebble":"Pokémon",
    "Crustle":"Pokémon",
    "Scraggy":"Pokémon",
    "Scrafty":"Pokémon",
    "Sigilyph":"Pokémon",
    "Yamask":"Pokémon",
    "Cofagrigus":"Pokémon",
    "Tirtouga":"Pokémon",
    "Carracosta":"Pokémon",
    "Archen":"Pokémon",
    "Archeops":"Pokémon",
    "Trubbish":"Pokémon",
    "Garbodor":"Pokémon",
    "Zorua":"Pokémon",
    "Zoroark":"Pokémon",
    "Minccino":"Pokémon",
    "Cinccino":"Pokémon",
    "Gothita":"Pokémon",
    "Gothorita":"Pokémon",
    "Gothitelle":"Pokémon",
    "Solosis":"Pokémon",
    "Duosion":"Pokémon",
    "Reuniclus":"Pokémon",
    "Ducklett":"Pokémon",
    "Swanna":"Pokémon",
    "Vanillite":"Pokémon",
    "Vanillish":"Pokémon",
    "Vanilluxe":"Pokémon",
    "Deerling":"Pokémon",
    "Sawsbuck":"Pokémon",
    "Emolga":"Pokémon",
    "Karrablast":"Pokémon",
    "Escavalier":"Pokémon",
    "Foongus":"Pokémon",
    "Amoonguss":"Pokémon",
    "Frillish":"Pokémon",
    "Jellicent":"Pokémon",
    "Alomomola":"Pokémon",
    "Joltik":"Pokémon",
    "Galvantula":"Pokémon",
    "Ferroseed":"Pokémon",
    "Ferrothorn":"Pokémon",
    "Klink":"Pokémon",
    "Klang":"Pokémon",
    "Klinklang":"Pokémon",
    "Tynamo":"Pokémon",
    "Eelektrik":"Pokémon",
    "Eelektross":"Pokémon",
    "Elgyem":"Pokémon",
    "Beheeyem":"Pokémon",
    "Litwick":"Pokémon",
    "Lampent":"Pokémon",
    "Chandelure":"Pokémon",
    "Axew":"Pokémon",
    "Fraxure":"Pokémon",
    "Haxorus":"Pokémon",
    "Cubchoo":"Pokémon",
    "Beartic":"Pokémon",
    "Cryogonal":"Pokémon",
    "Shelmet":"Pokémon",
    "Accelgor":"Pokémon",
    "Stunfisk":"Pokémon",
    "Mienfoo":"Pokémon",
    "Mienshao":"Pokémon",
    "Druddigon":"Pokémon",
    "Golett":"Pokémon",
    "Golurk":"Pokémon",
    "Pawniard":"Pokémon",
    "Bisharp":"Pokémon",
    "Bouffalant":"Pokémon",
    "Rufflet":"Pokémon",
    "Braviary":"Pokémon",
    "Vullaby":"Pokémon",
    "Mandibuzz":"Pokémon",
    "Heatmor":"Pokémon",
    "Durant":"Pokémon",
    "Deino":"Pokémon",
    "Zweilous":"Pokémon",
    "Hydreigon":"Pokémon",
    "Larvesta":"Pokémon",
    "Volcarona":"Pokémon",
    "Cobalion":"Pokémon",
    "Terrakion":"Pokémon",
    "Virizion":"Pokémon",
    "Tornadus":"Pokémon",
    "Tornadus-Therian":"Pokémon",
    "Thundurus":"Pokémon",
    "Thundurus-Therian":"Pokémon",
    "Reshiram":"Pokémon",
    "Zekrom":"Pokémon",
    "Landorus":"Pokémon",
    "Landorus-Therian":"Pokémon",
    "Kyurem":"Pokémon",
    "Kyurem-Black":"Pokémon",
    "Kyurem-White":"Pokémon",
    "Keldeo":"Pokémon",
    "Keldeo-Resolute":"Pokémon",
    "Meloetta":"Pokémon",
    "Meloetta-Pirouette":"Pokémon",
    "Genesect":"Pokémon",
    "Genesect-Douse":"Pokémon",
    "Genesect-Shock":"Pokémon",
    "Genesect-Burn":"Pokémon",
    "Genesect-Chill":"Pokémon",
    "Chespin":"Pokémon",
    "Quilladin":"Pokémon",
    "Chesnaught":"Pokémon",
    "Fennekin":"Pokémon",
    "Braixen":"Pokémon",
    "Delphox":"Pokémon",
    "Froakie":"Pokémon",
    "Frogadier":"Pokémon",
    "Greninja":"Pokémon",
    "Bunnelby":"Pokémon",
    "Diggersby":"Pokémon",
    "Fletchling":"Pokémon",
    "Fletchinder":"Pokémon",
    "Talonflame":"Pokémon",
    "Scatterbug":"Pokémon",
    "Spewpa":"Pokémon",
    "Vivillon":"Pokémon",
    "Litleo":"Pokémon",
    "Pyroar":"Pokémon",
    "Flabebe":"Pokémon",
    "Floette":"Pokémon",
    "Floette-Eternal-Flower":"Pokémon",
    "Florges":"Pokémon",
    "Skiddo":"Pokémon",
    "Gogoat":"Pokémon",
    "Pancham":"Pokémon",
    "Pangoro":"Pokémon",
    "Furfrou":"Pokémon",
    "Espurr":"Pokémon",
    "Meowstic":"Pokémon",
    "Meowstic-F":"Pokémon",
    "Honedge":"Pokémon",
    "Doublade":"Pokémon",
    "Aegislash":"Pokémon",
    "Aegislash-Blade":"Pokémon",
    "Spritzee":"Pokémon",
    "Aromatisse":"Pokémon",
    "Swirlix":"Pokémon",
    "Slurpuff":"Pokémon",
    "Inkay":"Pokémon",
    "Malamar":"Pokémon",
    "Binacle":"Pokémon",
    "Barbaracle":"Pokémon",
    "Skrelp":"Pokémon",
    "Dragalge":"Pokémon",
    "Clauncher":"Pokémon",
    "Clawitzer":"Pokémon",
    "Helioptile":"Pokémon",
    "Heliolisk":"Pokémon",
    "Tyrunt":"Pokémon",
    "Tyrantrum":"Pokémon",
    "Amaura":"Pokémon",
    "Aurorus":"Pokémon",
    "Sylveon":"Pokémon",
    "Hawlucha":"Pokémon",
    "Dedenne":"Pokémon",
    "Carbink":"Pokémon",
    "Goomy":"Pokémon",
    "Sliggoo":"Pokémon",
    "Goodra":"Pokémon",
    "Klefki":"Pokémon",
    "Phantump":"Pokémon",
    "Trevenant":"Pokémon",
    "Pumpkaboo":"Pokémon",
    "Pumpkaboo-Small":"Pokémon",
    "Pumpkaboo-Large":"Pokémon",
    "Pumpkaboo-Super":"Pokémon",
    "Gourgeist":"Pokémon",
    "Gourgeist-Small":"Pokémon",
    "Gourgeist-Large":"Pokémon",
    "Gourgeist-Super":"Pokémon",
    "Bergmite":"Pokémon",
    "Avalugg":"Pokémon",
    "Noibat":"Pokémon",
    "Noivern":"Pokémon",
    "Xerneas":"Pokémon",
    "Yveltal":"Pokémon",
    "Zygarde":"Pokémon",
    "Diancie":"Pokémon",
    "Diancie-Mega":"Pokémon",
    "Hoopa":"Pokémon",
    "Hoopa-Unbound":"Pokémon",
    "Volcanion":"Pokémon",
    "Missingno.":"Pokémon",
    "Tomohawk":"Pokémon",
    "Necturna":"Pokémon",
    "Mollux":"Pokémon",
    "Aurumoth":"Pokémon",
    "Malaconda":"Pokémon",
    "Cawmodore":"Pokémon",
    "Volkraken":"Pokémon",
    "Plasmanta":"Pokémon",
    "Naviathan":"Pokémon",
    "Syclant":"Pokémon",
    "Revenankh":"Pokémon",
    "Pyroak":"Pokémon",
    "Fidgit":"Pokémon",
    "Stratagem":"Pokémon",
    "Arghonaut":"Pokémon",
    "Kitsunoh":"Pokémon",
    "Cyclohm":"Pokémon",
    "Colossoil":"Pokémon",
    "Krilowatt":"Pokémon",
    "Voodoom":"Pokémon",
    "Absorb":"Pokémon Move",
    "Acid":"Pokémon Move",
    "Acid Armor":"Pokémon Move",
    "Acid Spray":"Pokémon Move",
    "Acrobatics":"Pokémon Move",
    "Acupressure":"Pokémon Move",
    "Aerial Ace":"Pokémon Move",
    "Aeroblast":"Pokémon Move",
    "After You":"Pokémon Move",
    "Agility":"Pokémon Move",
    "Air Cutter":"Pokémon Move",
    "Air Slash":"Pokémon Move",
    "Ally Switch":"Pokémon Move",
    "Amnesia":"Pokémon Move",
    "Ancient Power":"Pokémon Move",
    "Aqua Jet":"Pokémon Move",
    "Aqua Ring":"Pokémon Move",
    "Aqua Tail":"Pokémon Move",
    "Arm Thrust":"Pokémon Move",
    "Aromatherapy":"Pokémon Move",
    "Aromatic Mist":"Pokémon Move",
    "Assist":"Pokémon Move",
    "Assurance":"Pokémon Move",
    "Astonish":"Pokémon Move",
    "Attack Order":"Pokémon Move",
    "Attract":"Pokémon Move",
    "Aura Sphere":"Pokémon Move",
    "Aurora Beam":"Pokémon Move",
    "Autotomize":"Pokémon Move",
    "Avalanche":"Pokémon Move",
    "Baby-Doll Eyes":"Pokémon Move",
    "Barrage":"Pokémon Move",
    "Barrier":"Pokémon Move",
    "Baton Pass":"Pokémon Move",
    "Beat Up":"Pokémon Move",
    "Belch":"Pokémon Move",
    "Belly Drum":"Pokémon Move",
    "Bestow":"Pokémon Move",
    "Bide":"Pokémon Move",
    "Bind":"Pokémon Move",
    "Bite":"Pokémon Move",
    "Blast Burn":"Pokémon Move",
    "Blaze Kick":"Pokémon Move",
    "Blizzard":"Pokémon Move",
    "Block":"Pokémon Move",
    "Blue Flare":"Pokémon Move",
    "Body Slam":"Pokémon Move",
    "Bolt Strike":"Pokémon Move",
    "Bone Club":"Pokémon Move",
    "Bone Rush":"Pokémon Move",
    "Bonemerang":"Pokémon Move",
    "Boomburst":"Pokémon Move",
    "Bounce":"Pokémon Move",
    "Brave Bird":"Pokémon Move",
    "Brick Break":"Pokémon Move",
    "Brine":"Pokémon Move",
    "Bubble":"Pokémon Move",
    "Bubble Beam":"Pokémon Move",
    "Bug Bite":"Pokémon Move",
    "Bug Buzz":"Pokémon Move",
    "Bulk Up":"Pokémon Move",
    "Bulldoze":"Pokémon Move",
    "Bullet Punch":"Pokémon Move",
    "Bullet Seed":"Pokémon Move",
    "Calm Mind":"Pokémon Move",
    "Camouflage":"Pokémon Move",
    "Captivate":"Pokémon Move",
    "Celebrate":"Pokémon Move",
    "Charge":"Pokémon Move",
    "Charge Beam":"Pokémon Move",
    "Charm":"Pokémon Move",
    "Chatter":"Pokémon Move",
    "Chip Away":"Pokémon Move",
    "Circle Throw":"Pokémon Move",
    "Clamp":"Pokémon Move",
    "Clear Smog":"Pokémon Move",
    "Close Combat":"Pokémon Move",
    "Coil":"Pokémon Move",
    "Comet Punch":"Pokémon Move",
    "Confide":"Pokémon Move",
    "Confuse Ray":"Pokémon Move",
    "Confusion":"Pokémon Move",
    "Constrict":"Pokémon Move",
    "Conversion":"Pokémon Move",
    "Conversion 2":"Pokémon Move",
    "Copycat":"Pokémon Move",
    "Cosmic Power":"Pokémon Move",
    "Cotton Guard":"Pokémon Move",
    "Cotton Spore":"Pokémon Move",
    "Counter":"Pokémon Move",
    "Covet":"Pokémon Move",
    "Crabhammer":"Pokémon Move",
    "Crafty Shield":"Pokémon Move",
    "Cross Chop":"Pokémon Move",
    "Cross Poison":"Pokémon Move",
    "Crunch":"Pokémon Move",
    "Crush Claw":"Pokémon Move",
    "Crush Grip":"Pokémon Move",
    "Curse":"Pokémon Move",
    "Cut":"Pokémon Move",
    "Dark Pulse":"Pokémon Move",
    "Dark Void":"Pokémon Move",
    "Dazzling Gleam":"Pokémon Move",
    "Defend Order":"Pokémon Move",
    "Defense Curl":"Pokémon Move",
    "Defog":"Pokémon Move",
    "Destiny Bond":"Pokémon Move",
    "Detect":"Pokémon Move",
    "Diamond Storm":"Pokémon Move",
    "Dig":"Pokémon Move",
    "Disable":"Pokémon Move",
    "Disarming Voice":"Pokémon Move",
    "Discharge":"Pokémon Move",
    "Dive":"Pokémon Move",
    "Dizzy Punch":"Pokémon Move",
    "Doom Desire":"Pokémon Move",
    "Double-Edge":"Pokémon Move",
    "Double Hit":"Pokémon Move",
    "Double Kick":"Pokémon Move",
    "Double Slap":"Pokémon Move",
    "Double Team":"Pokémon Move",
    "Draco Meteor":"Pokémon Move",
    "Dragon Ascent":"Pokémon Move",
    "Dragon Breath":"Pokémon Move",
    "Dragon Claw":"Pokémon Move",
    "Dragon Dance":"Pokémon Move",
    "Dragon Pulse":"Pokémon Move",
    "Dragon Rage":"Pokémon Move",
    "Dragon Rush":"Pokémon Move",
    "Dragon Tail":"Pokémon Move",
    "Draining Kiss":"Pokémon Move",
    "Drain Punch":"Pokémon Move",
    "Dream Eater":"Pokémon Move",
    "Drill Peck":"Pokémon Move",
    "Drill Run":"Pokémon Move",
    "Dual Chop":"Pokémon Move",
    "Dynamic Punch":"Pokémon Move",
    "Earth Power":"Pokémon Move",
    "Earthquake":"Pokémon Move",
    "Echoed Voice":"Pokémon Move",
    "Eerie Impulse":"Pokémon Move",
    "Egg Bomb":"Pokémon Move",
    "Electric Terrain":"Pokémon Move",
    "Electrify":"Pokémon Move",
    "Electro Ball":"Pokémon Move",
    "Electroweb":"Pokémon Move",
    "Embargo":"Pokémon Move",
    "Ember":"Pokémon Move",
    "Encore":"Pokémon Move",
    "Endeavor":"Pokémon Move",
    "Endure":"Pokémon Move",
    "Energy Ball":"Pokémon Move",
    "Entrainment":"Pokémon Move",
    "Eruption":"Pokémon Move",
    "Explosion":"Pokémon Move",
    "Extrasensory":"Pokémon Move",
    "Extreme Speed":"Pokémon Move",
    "Facade":"Pokémon Move",
    "Feint Attack":"Pokémon Move",
    "Fairy Lock":"Pokémon Move",
    "Fairy Wind":"Pokémon Move",
    "Fake Out":"Pokémon Move",
    "Fake Tears":"Pokémon Move",
    "False Swipe":"Pokémon Move",
    "Feather Dance":"Pokémon Move",
    "Feint":"Pokémon Move",
    "Fell Stinger":"Pokémon Move",
    "Fiery Dance":"Pokémon Move",
    "Final Gambit":"Pokémon Move",
    "Fire Blast":"Pokémon Move",
    "Fire Fang":"Pokémon Move",
    "Fire Pledge":"Pokémon Move",
    "Fire Punch":"Pokémon Move",
    "Fire Spin":"Pokémon Move",
    "Fissure":"Pokémon Move",
    "Flail":"Pokémon Move",
    "Flame Burst":"Pokémon Move",
    "Flame Charge":"Pokémon Move",
    "Flame Wheel":"Pokémon Move",
    "Flamethrower":"Pokémon Move",
    "Flare Blitz":"Pokémon Move",
    "Flash":"Pokémon Move",
    "Flash Cannon":"Pokémon Move",
    "Flatter":"Pokémon Move",
    "Fling":"Pokémon Move",
    "Flower Shield":"Pokémon Move",
    "Fly":"Pokémon Move",
    "Flying Press":"Pokémon Move",
    "Focus Blast":"Pokémon Move",
    "Focus Energy":"Pokémon Move",
    "Focus Punch":"Pokémon Move",
    "Follow Me":"Pokémon Move",
    "Force Palm":"Pokémon Move",
    "Foresight":"Pokémon Move",
    "Forest's Curse":"Pokémon Move",
    "Foul Play":"Pokémon Move",
    "Freeze-Dry":"Pokémon Move",
    "Freeze Shock":"Pokémon Move",
    "Frenzy Plant":"Pokémon Move",
    "Frost Breath":"Pokémon Move",
    "Frustration":"Pokémon Move",
    "Fury Attack":"Pokémon Move",
    "Fury Cutter":"Pokémon Move",
    "Fury Swipes":"Pokémon Move",
    "Fusion Bolt":"Pokémon Move",
    "Fusion Flare":"Pokémon Move",
    "Future Sight":"Pokémon Move",
    "Gastro Acid":"Pokémon Move",
    "Gear Grind":"Pokémon Move",
    "Geomancy":"Pokémon Move",
    "Giga Drain":"Pokémon Move",
    "Giga Impact":"Pokémon Move",
    "Glaciate":"Pokémon Move",
    "Glare":"Pokémon Move",
    "Grass Knot":"Pokémon Move",
    "Grass Pledge":"Pokémon Move",
    "Grass Whistle":"Pokémon Move",
    "Grassy Terrain":"Pokémon Move",
    "Gravity":"Pokémon Move",
    "Growl":"Pokémon Move",
    "Growth":"Pokémon Move",
    "Grudge":"Pokémon Move",
    "Guard Split":"Pokémon Move",
    "Guard Swap":"Pokémon Move",
    "Guillotine":"Pokémon Move",
    "Gunk Shot":"Pokémon Move",
    "Gust":"Pokémon Move",
    "Gyro Ball":"Pokémon Move",
    "Hail":"Pokémon Move",
    "Hammer Arm":"Pokémon Move",
    "Happy Hour":"Pokémon Move",
    "Harden":"Pokémon Move",
    "Haze":"Pokémon Move",
    "Head Charge":"Pokémon Move",
    "Head Smash":"Pokémon Move",
    "Headbutt":"Pokémon Move",
    "Heal Bell":"Pokémon Move",
    "Heal Block":"Pokémon Move",
    "Heal Order":"Pokémon Move",
    "Heal Pulse":"Pokémon Move",
    "Healing Wish":"Pokémon Move",
    "Heart Stamp":"Pokémon Move",
    "Heart Swap":"Pokémon Move",
    "Heat Crash":"Pokémon Move",
    "Heat Wave":"Pokémon Move",
    "Heavy Slam":"Pokémon Move",
    "Helping Hand":"Pokémon Move",
    "Hex":"Pokémon Move",
    "Hidden Power":"Pokémon Move",
    "Hidden Power Bug":"Pokémon Move",
    "Hidden Power Dark":"Pokémon Move",
    "Hidden Power Dragon":"Pokémon Move",
    "Hidden Power Electric":"Pokémon Move",
    "Hidden Power Fighting":"Pokémon Move",
    "Hidden Power Fire":"Pokémon Move",
    "Hidden Power Flying":"Pokémon Move",
    "Hidden Power Ghost":"Pokémon Move",
    "Hidden Power Grass":"Pokémon Move",
    "Hidden Power Ground":"Pokémon Move",
    "Hidden Power Ice":"Pokémon Move",
    "Hidden Power Poison":"Pokémon Move",
    "Hidden Power Psychic":"Pokémon Move",
    "Hidden Power Rock":"Pokémon Move",
    "Hidden Power Steel":"Pokémon Move",
    "Hidden Power Water":"Pokémon Move",
    "High Jump Kick":"Pokémon Move",
    "Hold Back":"Pokémon Move",
    "Hold Hands":"Pokémon Move",
    "Hone Claws":"Pokémon Move",
    "Horn Attack":"Pokémon Move",
    "Horn Drill":"Pokémon Move",
    "Horn Leech":"Pokémon Move",
    "Howl":"Pokémon Move",
    "Hurricane":"Pokémon Move",
    "Hydro Cannon":"Pokémon Move",
    "Hydro Pump":"Pokémon Move",
    "Hyper Beam":"Pokémon Move",
    "Hyper Fang":"Pokémon Move",
    "Hyperspace Fury":"Pokémon Move",
    "Hyperspace Hole":"Pokémon Move",
    "Hyper Voice":"Pokémon Move",
    "Hypnosis":"Pokémon Move",
    "Ice Ball":"Pokémon Move",
    "Ice Beam":"Pokémon Move",
    "Ice Burn":"Pokémon Move",
    "Ice Fang":"Pokémon Move",
    "Ice Punch":"Pokémon Move",
    "Ice Shard":"Pokémon Move",
    "Icicle Crash":"Pokémon Move",
    "Icicle Spear":"Pokémon Move",
    "Icy Wind":"Pokémon Move",
    "Imprison":"Pokémon Move",
    "Incinerate":"Pokémon Move",
    "Inferno":"Pokémon Move",
    "Infestation":"Pokémon Move",
    "Ingrain":"Pokémon Move",
    "Ion Deluge":"Pokémon Move",
    "Iron Defense":"Pokémon Move",
    "Iron Head":"Pokémon Move",
    "Iron Tail":"Pokémon Move",
    "Judgment":"Pokémon Move",
    "Jump Kick":"Pokémon Move",
    "Karate Chop":"Pokémon Move",
    "Kinesis":"Pokémon Move",
    "King's Shield":"Pokémon Move",
    "Knock Off":"Pokémon Move",
    "Land's Wrath":"Pokémon Move",
    "Last Resort":"Pokémon Move",
    "Lava Plume":"Pokémon Move",
    "Leaf Blade":"Pokémon Move",
    "Leaf Storm":"Pokémon Move",
    "Leaf Tornado":"Pokémon Move",
    "Leech Life":"Pokémon Move",
    "Leech Seed":"Pokémon Move",
    "Leer":"Pokémon Move",
    "Lick":"Pokémon Move",
    "Light of Ruin":"Pokémon Move",
    "Light Screen":"Pokémon Move",
    "Lock-On":"Pokémon Move",
    "Lovely Kiss":"Pokémon Move",
    "Low Kick":"Pokémon Move",
    "Low Sweep":"Pokémon Move",
    "Lucky Chant":"Pokémon Move",
    "Lunar Dance":"Pokémon Move",
    "Luster Purge":"Pokémon Move",
    "Mach Punch":"Pokémon Move",
    "Magic Coat":"Pokémon Move",
    "Magic Room":"Pokémon Move",
    "Magical Leaf":"Pokémon Move",
    "Magma Storm":"Pokémon Move",
    "Magnet Bomb":"Pokémon Move",
    "Magnetic Flux":"Pokémon Move",
    "Magnet Rise":"Pokémon Move",
    "Magnitude":"Pokémon Move",
    "Mat Block":"Pokémon Move",
    "Me First":"Pokémon Move",
    "Mean Look":"Pokémon Move",
    "Meditate":"Pokémon Move",
    "Mega Drain":"Pokémon Move",
    "Mega Kick":"Pokémon Move",
    "Mega Punch":"Pokémon Move",
    "Megahorn":"Pokémon Move",
    "Memento":"Pokémon Move",
    "Metal Burst":"Pokémon Move",
    "Metal Claw":"Pokémon Move",
    "Metal Sound":"Pokémon Move",
    "Meteor Mash":"Pokémon Move",
    "Milk Drink":"Pokémon Move",
    "Mimic":"Pokémon Move",
    "Mind Reader":"Pokémon Move",
    "Minimize":"Pokémon Move",
    "Miracle Eye":"Pokémon Move",
    "Mirror Coat":"Pokémon Move",
    "Mirror Move":"Pokémon Move",
    "Mirror Shot":"Pokémon Move",
    "Mist":"Pokémon Move",
    "Mist Ball":"Pokémon Move",
    "Misty Terrain":"Pokémon Move",
    "Moonblast":"Pokémon Move",
    "Moonlight":"Pokémon Move",
    "Morning Sun":"Pokémon Move",
    "Mud-Slap":"Pokémon Move",
    "Mud Bomb":"Pokémon Move",
    "Mud Shot":"Pokémon Move",
    "Mud Sport":"Pokémon Move",
    "Muddy Water":"Pokémon Move",
    "Mystical Fire":"Pokémon Move",
    "Nasty Plot":"Pokémon Move",
    "Natural Gift":"Pokémon Move",
    "Nature Power":"Pokémon Move",
    "Needle Arm":"Pokémon Move",
    "Night Daze":"Pokémon Move",
    "Night Shade":"Pokémon Move",
    "Night Slash":"Pokémon Move",
    "Nightmare":"Pokémon Move",
    "Noble Roar":"Pokémon Move",
    "Nuzzle":"Pokémon Move",
    "Oblivion Wing":"Pokémon Move",
    "Octazooka":"Pokémon Move",
    "Odor Sleuth":"Pokémon Move",
    "Ominous Wind":"Pokémon Move",
    "Origin Pulse":"Pokémon Move",
    "Outrage":"Pokémon Move",
    "Overheat":"Pokémon Move",
    "Pain Split":"Pokémon Move",
    "Parabolic Charge":"Pokémon Move",
    "Parting Shot":"Pokémon Move",
    "Pay Day":"Pokémon Move",
    "Payback":"Pokémon Move",
    "Peck":"Pokémon Move",
    "Perish Song":"Pokémon Move",
    "Petal Blizzard":"Pokémon Move",
    "Petal Dance":"Pokémon Move",
    "Phantom Force":"Pokémon Move",
    "Pin Missile":"Pokémon Move",
    "Play Nice":"Pokémon Move",
    "Play Rough":"Pokémon Move",
    "Pluck":"Pokémon Move",
    "Poison Fang":"Pokémon Move",
    "Poison Gas":"Pokémon Move",
    "Poison Jab":"Pokémon Move",
    "Poison Powder":"Pokémon Move",
    "Poison Sting":"Pokémon Move",
    "Poison Tail":"Pokémon Move",
    "Pound":"Pokémon Move",
    "Powder":"Pokémon Move",
    "Powder Snow":"Pokémon Move",
    "Power Gem":"Pokémon Move",
    "Power Split":"Pokémon Move",
    "Power Swap":"Pokémon Move",
    "Power Trick":"Pokémon Move",
    "Power-Up Punch":"Pokémon Move",
    "Power Whip":"Pokémon Move",
    "Precipice Blades":"Pokémon Move",
    "Present":"Pokémon Move",
    "Protect":"Pokémon Move",
    "Psybeam":"Pokémon Move",
    "Psych Up":"Pokémon Move",
    "Psychic":"Pokémon Move",
    "Psycho Boost":"Pokémon Move",
    "Psycho Cut":"Pokémon Move",
    "Psycho Shift":"Pokémon Move",
    "Psyshock":"Pokémon Move",
    "Psystrike":"Pokémon Move",
    "Psywave":"Pokémon Move",
    "Punishment":"Pokémon Move",
    "Pursuit":"Pokémon Move",
    "Quash":"Pokémon Move",
    "Quick Attack":"Pokémon Move",
    "Quick Guard":"Pokémon Move",
    "Quiver Dance":"Pokémon Move",
    "Rage":"Pokémon Move",
    "Rage Powder":"Pokémon Move",
    "Rain Dance":"Pokémon Move",
    "Rapid Spin":"Pokémon Move",
    "Razor Leaf":"Pokémon Move",
    "Razor Shell":"Pokémon Move",
    "Razor Wind":"Pokémon Move",
    "Recover":"Pokémon Move",
    "Recycle":"Pokémon Move",
    "Reflect":"Pokémon Move",
    "Reflect Type":"Pokémon Move",
    "Refresh":"Pokémon Move",
    "Relic Song":"Pokémon Move",
    "Rest":"Pokémon Move",
    "Retaliate":"Pokémon Move",
    "Return":"Pokémon Move",
    "Revenge":"Pokémon Move",
    "Reversal":"Pokémon Move",
    "Roar":"Pokémon Move",
    "Roar of Time":"Pokémon Move",
    "Rock Blast":"Pokémon Move",
    "Rock Climb":"Pokémon Move",
    "Rock Polish":"Pokémon Move",
    "Rock Slide":"Pokémon Move",
    "Rock Smash":"Pokémon Move",
    "Rock Throw":"Pokémon Move",
    "Rock Tomb":"Pokémon Move",
    "Rock Wrecker":"Pokémon Move",
    "Role Play":"Pokémon Move",
    "Rolling Kick":"Pokémon Move",
    "Rollout":"Pokémon Move",
    "Roost":"Pokémon Move",
    "Rototiller":"Pokémon Move",
    "Round":"Pokémon Move",
    "Sacred Fire":"Pokémon Move",
    "Sacred Sword":"Pokémon Move",
    "Safeguard":"Pokémon Move",
    "Sand Attack":"Pokémon Move",
    "Sand Tomb":"Pokémon Move",
    "Sandstorm":"Pokémon Move",
    "Scald":"Pokémon Move",
    "Scary Face":"Pokémon Move",
    "Scratch":"Pokémon Move",
    "Screech":"Pokémon Move",
    "Searing Shot":"Pokémon Move",
    "Secret Power":"Pokémon Move",
    "Secret Sword":"Pokémon Move",
    "Seed Bomb":"Pokémon Move",
    "Seed Flare":"Pokémon Move",
    "Seismic Toss":"Pokémon Move",
    "Self-Destruct":"Pokémon Move",
    "Shadow Ball":"Pokémon Move",
    "Shadow Claw":"Pokémon Move",
    "Shadow Force":"Pokémon Move",
    "Shadow Punch":"Pokémon Move",
    "Shadow Sneak":"Pokémon Move",
    "Sharpen":"Pokémon Move",
    "Sheer Cold":"Pokémon Move",
    "Shell Smash":"Pokémon Move",
    "Shift Gear":"Pokémon Move",
    "Shock Wave":"Pokémon Move",
    "Signal Beam":"Pokémon Move",
    "Silver Wind":"Pokémon Move",
    "Simple Beam":"Pokémon Move",
    "Sing":"Pokémon Move",
    "Sketch":"Pokémon Move",
    "Skill Swap":"Pokémon Move",
    "Skull Bash":"Pokémon Move",
    "Sky Attack":"Pokémon Move",
    "Sky Drop":"Pokémon Move",
    "Sky Uppercut":"Pokémon Move",
    "Slack Off":"Pokémon Move",
    "Slam":"Pokémon Move",
    "Slash":"Pokémon Move",
    "Sleep Powder":"Pokémon Move",
    "Sleep Talk":"Pokémon Move",
    "Sludge":"Pokémon Move",
    "Sludge Bomb":"Pokémon Move",
    "Sludge Wave":"Pokémon Move",
    "Smack Down":"Pokémon Move",
    "Smelling Salts":"Pokémon Move",
    "Smog":"Pokémon Move",
    "Smokescreen":"Pokémon Move",
    "Snarl":"Pokémon Move",
    "Snatch":"Pokémon Move",
    "Snore":"Pokémon Move",
    "Spiky Shield":"Pokémon Move",
    "Soak":"Pokémon Move",
    "Soft-Boiled":"Pokémon Move",
    "Solar Beam":"Pokémon Move",
    "Sonic Boom":"Pokémon Move",
    "Spacial Rend":"Pokémon Move",
    "Spark":"Pokémon Move",
    "Spider Web":"Pokémon Move",
    "Spike Cannon":"Pokémon Move",
    "Spikes":"Pokémon Move",
    "Spit Up":"Pokémon Move",
    "Spite":"Pokémon Move",
    "Splash":"Pokémon Move",
    "Spore":"Pokémon Move",
    "Stealth Rock":"Pokémon Move",
    "Steam Eruption":"Pokémon Move",
    "Steel Wing":"Pokémon Move",
    "Sticky Web":"Pokémon Move",
    "Stockpile":"Pokémon Move",
    "Stomp":"Pokémon Move",
    "Stone Edge":"Pokémon Move",
    "Stored Power":"Pokémon Move",
    "Storm Throw":"Pokémon Move",
    "Steamroller":"Pokémon Move",
    "Strength":"Pokémon Move",
    "String Shot":"Pokémon Move",
    "Struggle":"Pokémon Move",
    "Struggle Bug":"Pokémon Move",
    "Stun Spore":"Pokémon Move",
    "Submission":"Pokémon Move",
    "Substitute":"Pokémon Move",
    "Sucker Punch":"Pokémon Move",
    "Sunny Day":"Pokémon Move",
    "Super Fang":"Pokémon Move",
    "Superpower":"Pokémon Move",
    "Supersonic":"Pokémon Move",
    "Surf":"Pokémon Move",
    "Swagger":"Pokémon Move",
    "Swallow":"Pokémon Move",
    "Sweet Kiss":"Pokémon Move",
    "Sweet Scent":"Pokémon Move",
    "Swift":"Pokémon Move",
    "Switcheroo":"Pokémon Move",
    "Swords Dance":"Pokémon Move",
    "Synchronoise":"Pokémon Move",
    "Synthesis":"Pokémon Move",
    "Tackle":"Pokémon Move",
    "Tail Glow":"Pokémon Move",
    "Tail Slap":"Pokémon Move",
    "Tail Whip":"Pokémon Move",
    "Tailwind":"Pokémon Move",
    "Take Down":"Pokémon Move",
    "Taunt":"Pokémon Move",
    "Techno Blast":"Pokémon Move",
    "Teeter Dance":"Pokémon Move",
    "Telekinesis":"Pokémon Move",
    "Teleport":"Pokémon Move",
    "Thief":"Pokémon Move",
    "Thousand Arrows":"Pokémon Move",
    "Thousand Waves":"Pokémon Move",
    "Thrash":"Pokémon Move",
    "Thunder":"Pokémon Move",
    "Thunder Fang":"Pokémon Move",
    "Thunder Punch":"Pokémon Move",
    "Thunder Shock":"Pokémon Move",
    "Thunder Wave":"Pokémon Move",
    "Thunderbolt":"Pokémon Move",
    "Tickle":"Pokémon Move",
    "Topsy-Turvy":"Pokémon Move",
    "Torment":"Pokémon Move",
    "Toxic":"Pokémon Move",
    "Toxic Spikes":"Pokémon Move",
    "Transform":"Pokémon Move",
    "Tri Attack":"Pokémon Move",
    "Trick":"Pokémon Move",
    "Trick-or-Treat":"Pokémon Move",
    "Trick Room":"Pokémon Move",
    "Triple Kick":"Pokémon Move",
    "Trump Card":"Pokémon Move",
    "Twineedle":"Pokémon Move",
    "Twister":"Pokémon Move",
    "U-turn":"Pokémon Move",
    "Uproar":"Pokémon Move",
    "V-create":"Pokémon Move",
    "Vacuum Wave":"Pokémon Move",
    "Venom Drench":"Pokémon Move",
    "Venoshock":"Pokémon Move",
    "Vice Grip":"Pokémon Move",
    "Vine Whip":"Pokémon Move",
    "Vital Throw":"Pokémon Move",
    "Volt Switch":"Pokémon Move",
    "Volt Tackle":"Pokémon Move",
    "Wake-Up Slap":"Pokémon Move",
    "Water Gun":"Pokémon Move",
    "Water Pledge":"Pokémon Move",
    "Water Pulse":"Pokémon Move",
    "Water Sport":"Pokémon Move",
    "Water Spout":"Pokémon Move",
    "Waterfall":"Pokémon Move",
    "Water Shuriken":"Pokémon Move",
    "Weather Ball":"Pokémon Move",
    "Whirlpool":"Pokémon Move",
    "Whirlwind":"Pokémon Move",
    "Wide Guard":"Pokémon Move",
    "Wild Charge":"Pokémon Move",
    "Will-O-Wisp":"Pokémon Move",
    "Wing Attack":"Pokémon Move",
    "Wish":"Pokémon Move",
    "Withdraw":"Pokémon Move",
    "Wonder Room":"Pokémon Move",
    "Wood Hammer":"Pokémon Move",
    "Work Up":"Pokémon Move",
    "Worry Seed":"Pokémon Move",
    "Wrap":"Pokémon Move",
    "Wring Out":"Pokémon Move",
    "X-Scissor":"Pokémon Move",
    "Yawn":"Pokémon Move",
    "Zap Cannon":"Pokémon Move",
    "Zen Headbutt":"Pokémon Move",
    "Paleo Wave":"Pokémon Move",
    "Shadow Strike":"Pokémon Move",
    "Magikarp's Revenge":"Pokémon Move",
    "Abandoned Ship":"PKMN Location - Hoenn",
    "Altering Cave":"PKMN Location - Sevii Islands",
    "Amity Square":"PKMN Location - Sinnoh",
    "Ancient Tomb":"PKMN Location - Hoenn",
    "Artisan Cave":"PKMN Location - Hoenn",
    "Azure Bay":"PKMN Location - Kalos",
    "Battle Chateau":"PKMN Location - Kalos",
    "Battle Frontier":"PKMN Location - Sinnoh",
    "Battle Maison":"PKMN Location - Hoenn",
    "Battle Resort":"PKMN Location - Hoenn",
    "Battle Tower":"PKMN Location - Sinnoh",
    "Bell Tower":"PKMN Location - Johto",
    "Berry fields":"PKMN Location - Kalos",
    "Berry Forest":"PKMN Location - Sevii Islands",
    "Big Stadium":"PKMN Location - Unova",
    "Bike Shop":"PKMN Location - Kanto and Johto",
    "Birth Island":"PKMN Location - Sevii Islands",
    "Boon Island":"PKMN Location - Sevii Islands",
    "Brass/Burned Tower":"PKMN Location - Johto",
    "Castelia Sewers":"PKMN Location - Unova",
    "Cave of Origin":"PKMN Location - Hoenn",
    "Celadon Condominiums/Mansion":"PKMN Location - Kanto",
    "Celadon Department Store":"PKMN Location - Kanto",
    "Celadon Game Corner":"PKMN Location - Kanto",
    "Cerulean Cape":"PKMN Location - Kanto",
    "Cerulean Cave":"PKMN Location - Kanto",
    "Chamber of Emptiness":"PKMN Location - Kalos",
    "Chrono Island":"PKMN Location - Sevii Islands",
    "Citadark Isle":"PKMN Location - Orre",
    "Cliff Cave":"PKMN Location - Johto",
    "Connecting Cave":"PKMN Location - Kalos",
    "Cove Lily Motel":"PKMN Location - Hoenn",
    "Crescent Isle":"PKMN Location - Hoenn",
    "Desert Resort":"PKMN Location - Unova",
    "Desert Ruins":"PKMN Location - Hoenn",
    "Desert Underpass":"PKMN Location - Hoenn",
    "Devon Corporation":"PKMN Location - Hoenn",
    "Distortion World":"PKMN Location - Sinnoh",
    "Dotted Hole":"PKMN Location - Sevii Islands",
    "Dragon's Den":"PKMN Location - Johto",
    "Dreamyard":"PKMN Location - Unova",
    "Eterna Forest":"PKMN Location - Sinnoh",
    "Fabled Cave":"PKMN Location - Hoenn",
    "Faraway Island":"PKMN Location - Hoenn",
    "Fiery Path":"PKMN Location - Hoenn",
    "Floaroma Meadow":"PKMN Location - Sinnoh",
    "Floccesy Ranch":"PKMN Location - Unova",
    "Floe Island":"PKMN Location - Sevii Islands",
    "Flower Paradise":"PKMN Location - Sinnoh",
    "Fortune Island":"PKMN Location - Sevii Islands",
    "Friend Safari":"PKMN Location - Kalos",
    "Frost Cavern":"PKMN Location - Kalos",
    "Fullmoon Island":"PKMN Location - Sinnoh",
    "Glitter Lighthouse":"PKMN Location - Johto",
    "Glittering Cave":"PKMN Location - Kalos",
    "Global Terminal":"PKMN Location - Sinnoh",
    "Gnarled Den":"PKMN Location - Hoenn",
    "Goldenrod Department Store":"PKMN Location - Johto",
    "Goldenrod Game Corner":"PKMN Location - Johto",
    "Goldenrod Tunnel":"PKMN Location - Johto",
    "Granite Cave":"PKMN Location - Hoenn",
    "Great Marsh":"PKMN Location - Sinnoh",
    "Hall of Origin":"PKMN Location - Sinnoh",
    "Hallowed Tower":"PKMN Location - Sinnoh",
    "Ice Path":"PKMN Location - Johto",
    "Icefall Cave":"PKMN Location - Sevii Islands",
    "Iron Island":"PKMN Location - Sinnoh",
    "Island Cave":"PKMN Location - Hoenn",
    "Jagged Pass":"PKMN Location - Hoenn",
    "Joyful Game Corner":"PKMN Location - Sevii Islands",
    "Jubilife TV":"PKMN Location - Sinnoh",
    "Kalos Power Plant":"PKMN Location - Kalos",
    "Kin Island":"PKMN Location - Sevii Islands",
    "Knot Island":"PKMN Location - Sevii Islands",
    "Lake Acuity":"PKMN Location - Sinnoh",
    "Lake of Rage":"PKMN Location - Johto",
    "Lake Valor":"PKMN Location - Sinnoh",
    "Lake Verity":"PKMN Location - Sinnoh",
    "Lilycove Department Store":"PKMN Location - Hoenn",
    "Lilycove Museum":"PKMN Location - Hoenn",
    "Lost Cave":"PKMN Location - Sevii Islands",
    "Lost Hotel":"PKMN Location - Kalos",
    "Lysandre Labs":"PKMN Location - Kalos",
    "Marine Cave":"PKMN Location - Hoenn",
    "Mauville Game Corner":"PKMN Location - Hoenn",
    "Meteor Falls":"PKMN Location - Hoenn",
    "Mirage Cave":"PKMN Location - Hoenn",
    "Mirage Forest":"PKMN Location - Hoenn",
    "Mirage Island":"PKMN Location - Hoenn",
    "Mirage Mountain":"PKMN Location - Hoenn",
    "Mirage Tower":"PKMN Location - Hoenn",
    "MooMoo Farm":"PKMN Location - Johto",
    "Mossdeep Space Center":"PKMN Location - Hoenn",
    "Mt. Battle":"PKMN Location - Orre",
    "Mt. Chimney":"PKMN Location - Hoenn",
    "Mt. Coronet":"PKMN Location - Sinnoh",
    "Mt. Ember":"PKMN Location - Sevii Islands",
    "Mt. Moon":"PKMN Location - Kanto",
    "Mt. Moon Square":"PKMN Location - Kanto",
    "Mt. Mortar":"PKMN Location - Johto",
    "Mt. Pyre":"PKMN Location - Hoenn",
    "Mt. Silver":"PKMN Location - Johto",
    "Nameless Cavern":"PKMN Location - Hoenn",
    "National Park":"PKMN Location - Johto",
    "Navel Rock":"PKMN Location - Sevii Islands",
    "New Mauville":"PKMN Location - Hoenn",
    "Newmoon Island":"PKMN Location - Sinnoh",
    "Oceanic Museum":"PKMN Location - Hoenn",
    "Old Chateau":"PKMN Location - Sinnoh",
    "Oreburgh Gate":"PKMN Location - Sinnoh",
    "Oreburgh Mine":"PKMN Location - Sinnoh",
    "Oreburgh Mining Museum":"PKMN Location - Sinnoh",
    "P2 Laboratory":"PKMN Location - Unova",
    "Pal Park":"PKMN Location - Sinnoh",
    "Parfum Palace":"PKMN Location - Kalos",
    "Pathless Plain":"PKMN Location - Hoenn",
    "Pattern Bush":"PKMN Location - Sevii Islands",
    "Petalburg Woods":"PKMN Location - Hoenn",
    "Pewter Museum of Science":"PKMN Location - Kanto",
    "Pick a Peck of Colors Flower Shop":"PKMN Location - Sinnoh",
    "Pledge Grove":"PKMN Location - Unova",
    "Poké Ball Factory":"PKMN Location - Kalos",
    "Pokémon Communication Center":"PKMN Location - Johto",
    "Pokémon League Reception Gate":"PKMN Location - Kanto",
    "Pokémon Mansion":"PKMN Location - Kanto",
    "Pokémon Tower":"PKMN Location - Kanto",
    "Pokémon Trainer's School":"PKMN Location - Hoenn",
    "Pokémon Village":"PKMN Location - Kalos",
    "Pokéstar Studios":"PKMN Location - Unova",
    "Power Plant":"PKMN Location - Kanto",
    "Pretty Petal Flower Shop":"PKMN Location - Hoenn",
    "Pyrite Bldg":"PKMN Location - Orre",
    "Pyrite Cave":"PKMN Location - Orre",
    "Quest Island":"PKMN Location - Sevii Islands",
    "Rad Rickshaw's Cycle Shop":"PKMN Location - Sinnoh",
    "Radio Tower":"PKMN Location - Kanto",
    "Ravaged Path":"PKMN Location - Sinnoh",
    "Realgam Tower":"PKMN Location - Orre",
    "Reflection Cave":"PKMN Location - Kalos",
    "Relic Castle":"PKMN Location - Unova",
    "Ribbon Syndicate":"PKMN Location - Sinnoh",
    "Rock Tunnel":"PKMN Location - Kanto",
    "Rocket Hideout":"PKMN Location - Kanto",
    "Ruins of Alph":"PKMN Location - Johto",
    "Rusturf Tunnel":"PKMN Location - Hoenn",
    "Rydel's Cycles":"PKMN Location - Hoenn",
    "S.S. Anne":"PKMN Location - Kanto",
    "S.S. Aqua":"PKMN Location - Kanto and Johto",
    "S.S. Tidal":"PKMN Location - Hoenn",
    "Safari Zone":"PKMN Location - Kanto",
    "Santalune Forest":"PKMN Location - Kalos",
    "Scorched Slab":"PKMN Location - Hoenn",
    "Sea Cottage":"PKMN Location - Kanto",
    "Sea Mauville":"PKMN Location - Hoenn",
    "Sea Spirit's Den":"PKMN Location - Kalos",
    "Seafloor Cavern":"PKMN Location - Hoenn",
    "Seafoam Islands":"PKMN Location - Kanto",
    "Sealed Chamber":"PKMN Location - Hoenn",
    "Seaside Cycling Road":"PKMN Location - Hoenn",
    "Secret Islet":"PKMN Location - Hoenn",
    "Secret Meadow":"PKMN Location - Hoenn",
    "Secret Shore":"PKMN Location - Hoenn",
    "Sendoff Spring":"PKMN Location - Sinnoh",
    "Shoal Cave":"PKMN Location - Hoenn",
    "Silph Co.":"PKMN Location - Kanto",
    "Sky Pillar":"PKMN Location - Hoenn",
    "Slowpoke Well":"PKMN Location - Johto",
    "Small Court":"PKMN Location - Unova",
    "Southern Island":"PKMN Location - Hoenn",
    "Spear Pillar":"PKMN Location - Sinnoh",
    "Sprout Tower":"PKMN Location - Johto",
    "Stark Mountain":"PKMN Location - Sinnoh",
    "Stern's Shipyard":"PKMN Location - Hoenn",
    "Tanoby Chambers":"PKMN Location - Sevii Islands",
    "Team Aqua Hideout":"PKMN Location - Hoenn",
    "Team Flare Secret HQ":"PKMN Location - Kalos",
    "Team Magma Hideout":"PKMN Location - Hoenn",
    "Team Rocket HQ":"PKMN Location - Johto",
    "Terminus Cave":"PKMN Location - Kalos",
    "Terra Cave":"PKMN Location - Hoenn",
    "The Underground":"PKMN Location - Sinnoh",
    "Tohjo Falls":"PKMN Location - Kanto",
    "Tower of Mastery":"PKMN Location - Kalos",
    "Trackless Forest":"PKMN Location - Hoenn",
    "Trainer Hill":"PKMN Location - Hoenn",
    "Trick House":"PKMN Location - Hoenn",
    "Trophy Garden":"PKMN Location - Sinnoh",
    "Turnback Cave":"PKMN Location - Sinnoh",
    "Unknown Dungeon":"PKMN Location - Kalos",
    "Valley Windworks":"PKMN Location - Sinnoh",
    "Veilstone Department Store":"PKMN Location - Sinnoh",
    "Veilstone Game Corner":"PKMN Location - Sinnoh",
    "Victory Road":"PKMN Location - Unova",
    "Virbank Complex":"PKMN Location - Unova",
    "Viridian Forest":"PKMN Location - Kanto",
    "Vista Lighthouse":"PKMN Location - Sinnoh",
    "Wayward Cave":"PKMN Location - Sinnoh",
    "Weather Institute":"PKMN Location - Hoenn",
    "Wellspring Cave":"PKMN Location - Unova",
    "Whirl Islands":"PKMN Location - Johto"
}